/*
 * FormConfig.java
 *
 * Created on 20 de Novembro de 2005, 17:04
 */

package br.ufsc.linhasecores.ui;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author  xande
 */
public class FormConfig extends javax.swing.JDialog
{
   private boolean confirmou;
   
   /** Creates new form FormConfig */
   public FormConfig(java.awt.Frame parent, boolean modal)
   {
      super(parent, modal);
      initComponents();
      confirmou = false;
      btnOk.setDefaultCapable(true);
      getRootPane().setDefaultButton(btnOk);
   }
   
   
   /**
    * Sobrepondo o método setVisible da classe pai para
    * garantir que, se uma instância do diálogo for
    * reutilizada, o estado de confirmação seja falso
    * antes do formulário tornar-se visível.
    */
   public void setVisible(boolean b)
   {
      if (b)
      {
         confirmou = false;
      }
      super.setVisible(b);
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      selNumCores = new javax.swing.JSpinner();
      jLabel2 = new javax.swing.JLabel();
      selTamanho = new javax.swing.JSpinner();
      jPanel2 = new javax.swing.JPanel();
      btnOk = new javax.swing.JButton();
      btnCancelar = new javax.swing.JButton();

      FormListener formListener = new FormListener();

      setTitle("Configura\u00e7\u00e3o");
      setModal(true);
      setName("dlgConfig");
      setResizable(false);
      jPanel1.setLayout(new java.awt.GridBagLayout());

      jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "N\u00edvel de Dificuldade"));
      jLabel1.setFont(new java.awt.Font("Dialog", 0, 11));
      jLabel1.setText("N\u00famero de Cores:");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
      jPanel1.add(jLabel1, gridBagConstraints);

      selNumCores.setFont(new java.awt.Font("Dialog", 0, 11));
      selNumCores.setModel(new SpinnerNumberModel (5, 2, 7, 1));
      selNumCores.setPreferredSize(new java.awt.Dimension(40, 18));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
      jPanel1.add(selNumCores, gridBagConstraints);

      jLabel2.setFont(new java.awt.Font("Dialog", 0, 11));
      jLabel2.setText("Tamanho do Tabuleiro:");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
      jPanel1.add(jLabel2, gridBagConstraints);

      selTamanho.setFont(new java.awt.Font("Dialog", 0, 11));
      selTamanho.setModel(new SpinnerNumberModel (9, 5, 9, 1));
      selTamanho.setPreferredSize(new java.awt.Dimension(40, 18));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 1;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
      jPanel1.add(selTamanho, gridBagConstraints);

      getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

      jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

      jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
      btnOk.setFont(new java.awt.Font("Dialog", 0, 11));
      btnOk.setText("OK");
      btnOk.setPreferredSize(new java.awt.Dimension(81, 24));
      btnOk.addActionListener(formListener);

      jPanel2.add(btnOk);

      btnCancelar.setFont(new java.awt.Font("Dialog", 0, 11));
      btnCancelar.setText("Cancelar");
      btnCancelar.addActionListener(formListener);

      jPanel2.add(btnCancelar);

      getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

      pack();
   }

   // Code for dispatching events from components to event handlers.

   private class FormListener implements java.awt.event.ActionListener
   {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
         if (evt.getSource() == btnOk)
         {
            FormConfig.this.btnOkActionPerformed(evt);
         }
         else if (evt.getSource() == btnCancelar)
         {
            FormConfig.this.btnCancelarActionPerformed(evt);
         }
      }
   }
   // </editor-fold>//GEN-END:initComponents

   private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelarActionPerformed
   {//GEN-HEADEREND:event_btnCancelarActionPerformed
// TODO add your handling code here:
      confirmou = false;
      setVisible (false);
   }//GEN-LAST:event_btnCancelarActionPerformed

   private void btnOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOkActionPerformed
   {//GEN-HEADEREND:event_btnOkActionPerformed
// TODO add your handling code here:
      confirmou = true;
      setVisible(false);
   }//GEN-LAST:event_btnOkActionPerformed
   
   public boolean isConfirmado ()
   {
      return confirmou;
   }
   
   public void setNumCores (int numCores)
   {
      selNumCores.setValue( new Integer(numCores) );
   }
   
   public int getNumCores ()
   {
      SpinnerNumberModel model = (SpinnerNumberModel) selNumCores.getModel();
      return model.getNumber().intValue();
   }
   
   public void setTamanhoTabuleiro (int tamanho)
   {
      selTamanho.setValue (new Integer (tamanho));
   }
   
   public int getTamanho ()
   {
      SpinnerNumberModel model = (SpinnerNumberModel) selTamanho.getModel();
      return model.getNumber().intValue();
   }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new FormConfig(new javax.swing.JFrame(), true).setVisible(true);
         }
      });
   }
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   public javax.swing.JButton btnCancelar;
   public javax.swing.JButton btnOk;
   public javax.swing.JLabel jLabel1;
   public javax.swing.JLabel jLabel2;
   public javax.swing.JPanel jPanel1;
   public javax.swing.JPanel jPanel2;
   public javax.swing.JSpinner selNumCores;
   public javax.swing.JSpinner selTamanho;
   // End of variables declaration//GEN-END:variables
   
}
