/*
 * MainForm.java
 *
 * Created on 12 de Outubro de 2005, 12:08
 */

package br.ufsc.linhasecores.ui;

import br.ufsc.linhasecores.ui.ControladorJogo;

/**
 *
 * @author  xande
 */
public class MainForm extends javax.swing.JFrame
{
      
   /**
    * TableModel para o tabuleiro
    */
   VisaoTabuleiro visaoTabuleiro;
   ControladorJogo controlador;
   

   public VisaoTabuleiro getVisaoTabuleiro()
   {
      return visaoTabuleiro;
   }
   
   /** Creates new form MainForm */
   public MainForm (ControladorJogo c)
   {
      controlador = c;
      
      initTabuleiro();
      initComponents ();
      
      visaoTabuleiro.ajustarTabuleiro (areaTabuleiro);
      visaoTabuleiro.ajustarDisplayProximasBolas(areaProximasBolinhas);
      pack();
      setResizable(false);
   }
   
   public void redimensionar()
   {
      visaoTabuleiro.ajustarTabuleiro (areaTabuleiro);
      visaoTabuleiro.ajustarDisplayProximasBolas(areaProximasBolinhas);
      pack();
   }
   
   public void redesenharProximasBolinhas()
   {
      visaoTabuleiro.notificaDisplayModificado();
   }
   
   public void redesenharTabuleiro()
   {
      int max = controlador.getTamanhoTabuleiro();
      for ( int i=0; i < max; ++i )
      {
         for (int j=0; j < max; ++j)
         {
            redesenharPosicao (i,j);
         }
      } 
        
   }
   
   public void redesenharPosicao (int linha, int coluna)
   {
      visaoTabuleiro.redesenharPosicao (linha, coluna);
      areaTabuleiro.invalidate();
   }
   
   public void setMensagemErro (String msg)
   {
      lblMensagens.setText("<html><font color='red'>" + msg + "</font></html>");
   }
   
   public void limpaMensagem()
   {
      lblMensagens.setText ("");
   }
   
   public void setTextoPlacar (String txt)
   {
      lblPlacar.setText(txt);
   }
   
   /**
    * Inicialização do tabuleiro
    */
   private void initTabuleiro()
   {
      visaoTabuleiro = new VisaoTabuleiro(controlador);      
   }
   
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      java.awt.GridBagConstraints gridBagConstraints;

      statusBar = new javax.swing.JPanel();
      placar = new javax.swing.JPanel();
      lblPlacar = new javax.swing.JLabel();
      msgPane = new javax.swing.JPanel();
      lblMensagens = new javax.swing.JLabel();
      jPanel5 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      areaProximasBolinhas = new javax.swing.JTable();
      areaTabuleiro = new javax.swing.JTable();
      mainMenu = new javax.swing.JMenuBar();
      menuJogo = new javax.swing.JMenu();
      miJogoNovo = new javax.swing.JMenuItem();
      miJogoDesfazer = new javax.swing.JMenuItem();
      jSeparator1 = new javax.swing.JSeparator();
      miJogoConfigurar = new javax.swing.JMenuItem();
      miJogoRecordes = new javax.swing.JMenuItem();
      jSeparator2 = new javax.swing.JSeparator();
      miJogoSair = new javax.swing.JMenuItem();
      jMenu1 = new javax.swing.JMenu();
      miAjudaIndice = new javax.swing.JMenuItem();
      jSeparator3 = new javax.swing.JSeparator();
      miSobre = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Linhas e Cores");
      statusBar.setLayout(new java.awt.BorderLayout());

      statusBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      placar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
      lblPlacar.setFont(new java.awt.Font("Dialog", 0, 11));
      lblPlacar.setText("200 pontos");
      placar.add(lblPlacar);

      statusBar.add(placar, java.awt.BorderLayout.WEST);

      msgPane.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

      msgPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
      lblMensagens.setFont(new java.awt.Font("Dialog", 0, 11));
      lblMensagens.setText("Espa\u00e7o destinado a mensagens");
      msgPane.add(lblMensagens);

      statusBar.add(msgPane, java.awt.BorderLayout.CENTER);

      getContentPane().add(statusBar, java.awt.BorderLayout.SOUTH);

      jPanel5.setLayout(new java.awt.GridBagLayout());

      jPanel5.setMinimumSize(new java.awt.Dimension(150, 120));
      jPanel5.setPreferredSize(new java.awt.Dimension(150, 150));
      jLabel1.setFont(new java.awt.Font("Dialog", 0, 11));
      jLabel1.setLabelFor(areaProximasBolinhas);
      jLabel1.setText("Pr\u00f3ximas bolinhas:");
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 0;
      gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
      gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
      gridBagConstraints.insets = new java.awt.Insets(50, 3, 3, 3);
      jPanel5.add(jLabel1, gridBagConstraints);

      areaProximasBolinhas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
      areaProximasBolinhas.setModel(visaoTabuleiro.getProximasBolinhasTableModel());
      areaProximasBolinhas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
      areaProximasBolinhas.setPreferredSize(new java.awt.Dimension(122, 42));
      gridBagConstraints = new java.awt.GridBagConstraints();
      gridBagConstraints.gridx = 0;
      gridBagConstraints.gridy = 1;
      gridBagConstraints.insets = new java.awt.Insets(3, 3, 50, 3);
      jPanel5.add(areaProximasBolinhas, gridBagConstraints);

      getContentPane().add(jPanel5, java.awt.BorderLayout.EAST);

      areaTabuleiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
      areaTabuleiro.setModel(visaoTabuleiro.getTableModel());
      areaTabuleiro.addMouseListener(new java.awt.event.MouseAdapter()
      {
         public void mouseClicked(java.awt.event.MouseEvent evt)
         {
            areaTabuleiroMouseClicked(evt);
         }
      });

      getContentPane().add(areaTabuleiro, java.awt.BorderLayout.CENTER);

      menuJogo.setMnemonic('J');
      menuJogo.setText("Jogo");
      menuJogo.setFont(new java.awt.Font("Dialog", 0, 11));
      miJogoNovo.setFont(new java.awt.Font("Dialog", 0, 11));
      miJogoNovo.setMnemonic('N');
      miJogoNovo.setText("Novo");
      miJogoNovo.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            miJogoNovoActionPerformed(evt);
         }
      });

      menuJogo.add(miJogoNovo);

      miJogoDesfazer.setFont(new java.awt.Font("Dialog", 0, 11));
      miJogoDesfazer.setMnemonic('z');
      miJogoDesfazer.setText("Defazer jogada");
      miJogoDesfazer.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            miJogoDesfazerActionPerformed(evt);
         }
      });

      menuJogo.add(miJogoDesfazer);

      menuJogo.add(jSeparator1);

      miJogoConfigurar.setFont(new java.awt.Font("Dialog", 0, 11));
      miJogoConfigurar.setMnemonic('C');
      miJogoConfigurar.setText("Configurar");
      miJogoConfigurar.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            miJogoConfigurarActionPerformed(evt);
         }
      });

      menuJogo.add(miJogoConfigurar);

      miJogoRecordes.setFont(new java.awt.Font("Dialog", 0, 11));
      miJogoRecordes.setMnemonic('M');
      miJogoRecordes.setText("Mostrar recordes");
      miJogoRecordes.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            miJogoRecordesActionPerformed(evt);
         }
      });

      menuJogo.add(miJogoRecordes);

      menuJogo.add(jSeparator2);

      miJogoSair.setFont(new java.awt.Font("Dialog", 0, 11));
      miJogoSair.setMnemonic('r');
      miJogoSair.setText("Sair");
      miJogoSair.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            miJogoSairActionPerformed(evt);
         }
      });

      menuJogo.add(miJogoSair);

      mainMenu.add(menuJogo);

      jMenu1.setMnemonic('A');
      jMenu1.setText("Ajuda");
      jMenu1.setFont(new java.awt.Font("Dialog", 0, 11));
      miAjudaIndice.setFont(new java.awt.Font("Dialog", 0, 11));
      miAjudaIndice.setMnemonic('i');
      miAjudaIndice.setText("\u00cdndice");
      jMenu1.add(miAjudaIndice);

      jMenu1.add(jSeparator3);

      miSobre.setFont(new java.awt.Font("Dialog", 0, 11));
      miSobre.setMnemonic('s');
      miSobre.setText("Sobre o Linhas e Cores");
      jMenu1.add(miSobre);

      mainMenu.add(jMenu1);

      setJMenuBar(mainMenu);

      pack();
   }
   // </editor-fold>//GEN-END:initComponents

   private void miJogoRecordesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miJogoRecordesActionPerformed
   {//GEN-HEADEREND:event_miJogoRecordesActionPerformed
// TODO add your handling code here:
      MostradorRecords mostrador = new MostradorRecords (this, true, controlador.getRecords());
      mostrador.setVisible(true);
   }//GEN-LAST:event_miJogoRecordesActionPerformed

   private void miJogoDesfazerActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miJogoDesfazerActionPerformed
   {//GEN-HEADEREND:event_miJogoDesfazerActionPerformed
// TODO add your handling code here:
      controlador.desfazerJogada();
   }//GEN-LAST:event_miJogoDesfazerActionPerformed

   private void miJogoSairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miJogoSairActionPerformed
   {//GEN-HEADEREND:event_miJogoSairActionPerformed
// TODO add your handling code here:
      setVisible(false);
   }//GEN-LAST:event_miJogoSairActionPerformed

   private void areaTabuleiroMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_areaTabuleiroMouseClicked
   {//GEN-HEADEREND:event_areaTabuleiroMouseClicked
      // click com o mouse no tabuleiro!!!
      int linha = visaoTabuleiro.descobrirLinha (evt.getY());
      int coluna = visaoTabuleiro.descobrirColuna (evt.getX());
      
      controlador.clickTabuleiro (linha, coluna);
   }//GEN-LAST:event_areaTabuleiroMouseClicked

   private void miJogoConfigurarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miJogoConfigurarActionPerformed
   {//GEN-HEADEREND:event_miJogoConfigurarActionPerformed
      controlador.configurarJogo();
   }//GEN-LAST:event_miJogoConfigurarActionPerformed

   private void miJogoNovoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_miJogoNovoActionPerformed
   {//GEN-HEADEREND:event_miJogoNovoActionPerformed
      controlador.novoJogo();
   }//GEN-LAST:event_miJogoNovoActionPerformed
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTable areaProximasBolinhas;
   private javax.swing.JTable areaTabuleiro;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JPanel jPanel5;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JLabel lblMensagens;
   private javax.swing.JLabel lblPlacar;
   private javax.swing.JMenuBar mainMenu;
   private javax.swing.JMenu menuJogo;
   private javax.swing.JMenuItem miAjudaIndice;
   private javax.swing.JMenuItem miJogoConfigurar;
   private javax.swing.JMenuItem miJogoDesfazer;
   private javax.swing.JMenuItem miJogoNovo;
   private javax.swing.JMenuItem miJogoRecordes;
   private javax.swing.JMenuItem miJogoSair;
   private javax.swing.JMenuItem miSobre;
   private javax.swing.JPanel msgPane;
   private javax.swing.JPanel placar;
   private javax.swing.JPanel statusBar;
   // End of variables declaration//GEN-END:variables
   
}
