/*
 * MostradorRecords.java
 *
 * Created on 28 de Novembro de 2005, 22:25
 */

package br.ufsc.linhasecores.ui;

import br.ufsc.linhasecores.Record;
import java.awt.Font;
import javax.swing.JLabel;

/**
 *
 * @author  xande
 */
public class MostradorRecords extends javax.swing.JDialog
{
   
   /** Creates new form MostradorRecords */
   public MostradorRecords(java.awt.Frame parent, boolean modal, String[][] records)
   {
      super(parent, modal);
      initComponents();

      JLabel lbl;
      Font fontePadrao = new Font("Sans Serif", Font.PLAIN, 11);
      
      for (int i=0; i < records.length; i++)
      {
         lbl = new JLabel (records[i][0]);
         lbl.setFont(fontePadrao);
         pnNomes.add (lbl);

         lbl = new JLabel (records[i][1]);         
         lbl.setFont (fontePadrao);       
         lbl.setHorizontalAlignment(JLabel.CENTER);
         pnCores.add (lbl);

         lbl = new JLabel (records[i][2]);
         lbl.setFont(fontePadrao);
         lbl.setHorizontalAlignment(JLabel.CENTER);
         pnTamanho.add (lbl);

         lbl = new JLabel (records[i][3]);
         lbl.setFont(fontePadrao);
         lbl.setHorizontalAlignment(JLabel.RIGHT);
         pnPontos.add (lbl);
         
      }
      
      pack();
   }
   
   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
   private void initComponents()
   {
      jPanel1 = new javax.swing.JPanel();
      jLabel1 = new javax.swing.JLabel();
      jPanel2 = new javax.swing.JPanel();
      jButton1 = new javax.swing.JButton();
      jPanel3 = new javax.swing.JPanel();
      pnNomes = new javax.swing.JPanel();
      jLabel2 = new javax.swing.JLabel();
      jSeparator1 = new javax.swing.JSeparator();
      pnCores = new javax.swing.JPanel();
      jLabel3 = new javax.swing.JLabel();
      jSeparator2 = new javax.swing.JSeparator();
      pnTamanho = new javax.swing.JPanel();
      jLabel4 = new javax.swing.JLabel();
      jSeparator3 = new javax.swing.JSeparator();
      pnPontos = new javax.swing.JPanel();
      jLabel5 = new javax.swing.JLabel();
      jSeparator4 = new javax.swing.JSeparator();

      FormListener formListener = new FormListener();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("Recordes");
      jLabel1.setText("Maiores pontua\u00e7\u00f5es obtidas");
      jPanel1.add(jLabel1);

      getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

      jButton1.setText("Ok");
      jButton1.addActionListener(formListener);

      jPanel2.add(jButton1);

      getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

      jPanel3.setLayout(new java.awt.GridLayout(1, 4));

      jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
      pnNomes.setLayout(new java.awt.GridLayout(0, 1));

      jLabel2.setText("Nome");
      pnNomes.add(jLabel2);

      pnNomes.add(jSeparator1);

      jPanel3.add(pnNomes);

      pnCores.setLayout(new java.awt.GridLayout(0, 1));

      jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel3.setText("Cores");
      pnCores.add(jLabel3);

      pnCores.add(jSeparator2);

      jPanel3.add(pnCores);

      pnTamanho.setLayout(new java.awt.GridLayout(0, 1));

      jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
      jLabel4.setText("Tamanho      ");
      pnTamanho.add(jLabel4);

      pnTamanho.add(jSeparator3);

      jPanel3.add(pnTamanho);

      pnPontos.setLayout(new java.awt.GridLayout(0, 1));

      jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel5.setText("Pontos");
      pnPontos.add(jLabel5);

      pnPontos.add(jSeparator4);

      jPanel3.add(pnPontos);

      getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

      pack();
   }

   // Code for dispatching events from components to event handlers.

   private class FormListener implements java.awt.event.ActionListener
   {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
         if (evt.getSource() == jButton1)
         {
            MostradorRecords.this.jButton1ActionPerformed(evt);
         }
      }
   }
   // </editor-fold>//GEN-END:initComponents

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
   {//GEN-HEADEREND:event_jButton1ActionPerformed
// TODO add your handling code here:
      setVisible (false);
   }//GEN-LAST:event_jButton1ActionPerformed
   
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   public javax.swing.JButton jButton1;
   public javax.swing.JLabel jLabel1;
   public javax.swing.JLabel jLabel2;
   public javax.swing.JLabel jLabel3;
   public javax.swing.JLabel jLabel4;
   public javax.swing.JLabel jLabel5;
   public javax.swing.JPanel jPanel1;
   public javax.swing.JPanel jPanel2;
   public javax.swing.JPanel jPanel3;
   public javax.swing.JSeparator jSeparator1;
   public javax.swing.JSeparator jSeparator2;
   public javax.swing.JSeparator jSeparator3;
   public javax.swing.JSeparator jSeparator4;
   public javax.swing.JPanel pnCores;
   public javax.swing.JPanel pnNomes;
   public javax.swing.JPanel pnPontos;
   public javax.swing.JPanel pnTamanho;
   // End of variables declaration//GEN-END:variables
   
}
