package control;

import br.ufsc.inf.leobr.cliente.Jogada;
import java.util.ArrayList;
import java.util.Random;
import model.Card;
import model.Player;

public class Game implements Jogada {

    protected Player[] players;
    protected ArrayList<Card> blackCards;
    protected ArrayList<Card> whiteCards;
    protected boolean ongoingMatch;
    protected boolean connected;
    protected boolean allAnswered;
    protected Card blackCard;
    protected Random random;
    protected int currentCzar;
    protected String data;
    protected ArrayList<Card> answers;
    protected int round;
    protected int czarPosition;
    protected int currentPosition;
    protected boolean end;
    protected int championPosition;

    public Game(int numberPlayers) {
        random = new Random();
        players = new Player[numberPlayers];
        blackCards = new ArrayList<>();
        whiteCards = new ArrayList<>();
        answers = new ArrayList<>();
        round = 1;
        end = false;

    }

    public ArrayList<Card> getAnswers() {
        return answers;
    }

    public void setAnswers(ArrayList<Card> answers) {
        this.answers = answers;
    }

    public int getCurrentCzar() {
        return currentCzar;
    }

    public void setCurrentCzar(int currentCzar) {
        this.currentCzar = currentCzar;
    }

    public void prepare() {
        setOngoingMatch(true);
        for (int i = 0; i < players.length; i++) {
            players[i] = new Player();
        }
        fillDecks();
        fillHand();
        setCurrentPosition(1);
        setCurrentCzar(players.length);
    }

    public int getCzarPosition() {
        return czarPosition;
    }

    public void setCzarPosition(int czarPosition) {
        this.czarPosition = czarPosition;
    }

    public int getCurrentPosition() {
        return currentPosition;
    }

    public void setCurrentPosition(int currentPosition) {
        this.currentPosition = currentPosition;
    }

    public void randomBlack() {
        blackCard = blackCards.get(random.nextInt(blackCards.size()));
    }

    public Card randomWhite() {
        return whiteCards.get(random.nextInt(whiteCards.size()));
    }

    public void fillHand() {
        for (int i = 0; i < players.length; i++) {
            ArrayList<Card> aux = new ArrayList<>();
            for (int j = 0; j < 8; j++) {
                int rng = random.nextInt(whiteCards.size());
                aux.add(whiteCards.get(rng));
                whiteCards.remove(rng);
            }
            players[i].setDeck(aux);
        }
    }

    public Player[] getPlayers() {
        return players;
    }

    public ArrayList<Card> getBlackCards() {
        return blackCards;
    }

    public void setBlackCards(ArrayList<Card> blackCards) {
        this.blackCards = blackCards;
    }

    public ArrayList<Card> getWhiteCards() {
        return whiteCards;
    }

    public void setWhiteCards(ArrayList<Card> whiteCards) {
        this.whiteCards = whiteCards;
    }

    public boolean isOngoingMatch() {
        return ongoingMatch;
    }

    public void setOngoingMatch(boolean ongoingMatch) {
        this.ongoingMatch = ongoingMatch;
    }

    public Card getBlackCard() {
        return blackCard;
    }

    public void setBlackCard(Card blackCard) {
        this.blackCard = blackCard;
    }

    public boolean isConnected() {
        return connected;
    }

    public void setConnected(boolean connected) {
        this.connected = connected;
    }

    public Player getActualPlayer(int playerIndex) {
        return players[playerIndex - 1];
    }

    public boolean isAllAnswered() {
        return allAnswered;
    }

    public void setAllAnswered(boolean allAnswered) {
        this.allAnswered = allAnswered;
    }

    public int getRound() {
        return round;
    }

    public void setRound(int round) {
        this.round = round;
    }

    public void updateRound(int winner) {
        if (currentCzar < players.length) {
            setCurrentCzar(currentCzar+1);
        } else {
            setCurrentCzar(1);
        }
        updateCurrent();
        answers.clear();
        randomBlack();
        int points = players[winner].getPoints();
        players[winner].setPoints(++points);
        round++;
        if (points == 3) {
            this.championPosition = winner;
            end = true;
        }
    }
    
    public void updateCurrent() {
        if (currentPosition < players.length) {
            this.setCurrentPosition(currentPosition+1);
        } else {
            this.setCurrentPosition(1);
        }
    }

    public void fillDecks() {
        int i = 1;
        blackCards.add(new Card("_?  There's an app for that.", false));
        blackCards.add(new Card("Why can't I sleep at night?", false));
        blackCards.add(new Card("What's that smell?", false));
        blackCards.add(new Card("I got 99 problems but _ ain't one.", false));
        blackCards.add(new Card("Maybe she's born with it.  Maybe it's _.", false));
        blackCards.add(new Card("What's the next Happy Meal&copy; toy?", false));
        blackCards.add(new Card("Anthropologists have recently discovered a primitive tribe that worships _.", false));
        blackCards.add(new Card("It's a pity that kids these days are all getting involved with _.", false));
        blackCards.add(new Card("During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _.", false));
        blackCards.add(new Card("Alternative medicine is now embracing the curative powers of _.", false));
        blackCards.add(new Card("What's that sound?", false));
        blackCards.add(new Card("What ended my last relationship?", false));
        blackCards.add(new Card("MTV's new reality show features eight washed-up celebrities living with _.", false));
        blackCards.add(new Card("I drink to forget _.", false));
        blackCards.add(new Card("I'm sorry professor, but I couldn't complete my homework because of _.", false));
        blackCards.add(new Card("What is Batman's guilty pleasure?", false));
        blackCards.add(new Card("This is the way the world ends This is the way the world ends <br> Not with a bang but with _.", false));
        blackCards.add(new Card("What's a girl's best friend?", false));
        blackCards.add(new Card("TSA guidelines now prohibit _ on airplanes.", false));
        blackCards.add(new Card("_.  That's how I want to die.", false));
        blackCards.add(new Card("In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time.", false));
        blackCards.add(new Card("What does Dick Cheney prefer?", false));
        blackCards.add(new Card("Dear Abby, I'm having some trouble with _ and would like your advice.", false));
        blackCards.add(new Card("Instead of coal, Santa now gives the bad children _.", false));
        blackCards.add(new Card("What's the most emo?", false));
        blackCards.add(new Card("In 1,000 years when paper money is but a distant memory, _ will be our currency.", false));
        blackCards.add(new Card("What's the next superhero/sidekick duo?", false));
        blackCards.add(new Card("A romantic, candlelit dinner would be incomplete without _.", false));
        blackCards.add(new Card("_.  Becha can't have just one!", false));
        blackCards.add(new Card("White people like _.", false));
        blackCards.add(new Card("_.  High five, bro.", false));
        blackCards.add(new Card("Next from J.K. Rowling: Harry Potter and the Chamber of _.", false));
        blackCards.add(new Card("BILLY MAYS HERE FOR _.", false));
        blackCards.add(new Card("War!  What is it good for?", false));
        blackCards.add(new Card("During sex, I like to think about _.", false));
        blackCards.add(new Card("What are my parents hiding from me?", false));
        blackCards.add(new Card("What will always get you laid?", false));
        blackCards.add(new Card("In L.A. County Jail, word is you can trade 200 cigarettes for _.", false));
        blackCards.add(new Card("What did I bring back from Mexico?", false));
        blackCards.add(new Card("What don't you want to find in your Chinese food?", false));
        blackCards.add(new Card("What will I bring back in time to convince people that I am a powerful wizard?", false));
        blackCards.add(new Card("How am I maintaining my relationship status?", false));
        blackCards.add(new Card("_.  It's a trap!", false));
        blackCards.add(new Card("Coming to Broadway this season, _: The Musical.", false));
        blackCards.add(new Card("While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _.", false));
        blackCards.add(new Card("After the earthquake, Sean Penn brought _ to the people of Haiti.", false));
        blackCards.add(new Card("Next on ESPN2, the World Series of _.", false));
        blackCards.add(new Card("But before I kill you, Mr. Bond, I must show you _.", false));
        blackCards.add(new Card("What gives me uncontrollable gas?", false));
        blackCards.add(new Card("What do old people smell like?", false));
        blackCards.add(new Card("The class field trip was completely ruined by _.", false));
        blackCards.add(new Card("When Pharaoh remained unmoved, Moses called down a Plague of _.", false));
        blackCards.add(new Card("What's my secret power?", false));
        blackCards.add(new Card("What's there a ton of in heaven?", false));
        blackCards.add(new Card("What would grandma find disturbing, yet oddly charming?", false));
        blackCards.add(new Card("What did the U.S. airdrop to the children of Afghanistan?", false));
        blackCards.add(new Card("What helps Obama unwind?", false));
        blackCards.add(new Card("What did Vin Diesel eat for dinner?", false));
        blackCards.add(new Card("_: good to the last drop.", false));
        blackCards.add(new Card("Why am I sticky?", false));
        blackCards.add(new Card("What gets better with age?", false));
        blackCards.add(new Card("_: kid-tested, mother-approved.", false));
        blackCards.add(new Card("What's the crustiest?", false));
        blackCards.add(new Card("What's Teach for America using to inspire inner city students to succeed?", false));
        blackCards.add(new Card("Studies show that lab rats navigate mazes 50% faster after being exposed to _.", false));
        blackCards.add(new Card("Life for American Indians was forever changed when the White Man introduced them to _.", false));
        blackCards.add(new Card("Make a haiku.", false));
        blackCards.add(new Card("I do not know with what weapons World War III will be fought, but World War IV will be fought with _.", false));
        blackCards.add(new Card("Why do I hurt all over?", false));
        blackCards.add(new Card("What am I giving up for Lent?", false));
        blackCards.add(new Card("In Michael Jackson's final moments, he thought about _.", false));
        blackCards.add(new Card("In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _.", false));
        blackCards.add(new Card("When I am President of the United States, I will create the Department of _.", false));
        blackCards.add(new Card("When I am a billionaire, I shall erect a 50-foot statue to commemorate _.", false));
        blackCards.add(new Card("What's my anti-drug?", false));
        blackCards.add(new Card("What never fails to liven up the party?", false));
        blackCards.add(new Card("What's the new fad diet?", false));
        blackCards.add(new Card("Major League Baseball has banned _ for giving players an unfair advantage.", false));
        blackCards.add(new Card("My plan for world domination begins with _.", false));
        blackCards.add(new Card("The CIA now interrogates enemy agents by repeatedly subjecting them to _.", false));
        blackCards.add(new Card("In Rome, there are whisperings that the Vatican has a secret room devoted to _.", false));
        blackCards.add(new Card("Science will never explain _.", false));
        blackCards.add(new Card("When all else fails, I can always masturbate to _.", false));
        blackCards.add(new Card("I learned the hard way that you can't cheer up a grieving friend with _.", false));
        blackCards.add(new Card("In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated _.", false));
        blackCards.add(new Card("The socialist governments of Scandinavia have declared that access to _ is a basic human right.", false));
        blackCards.add(new Card("In his new self-produced album, Kanye West raps over the sounds of _.", false));
        blackCards.add(new Card("What's the gift that keeps on giving?", false));
        blackCards.add(new Card("Next season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only _ and his wits.", false));
        blackCards.add(new Card("When I pooped, what came out of my butt?", false));
        blackCards.add(new Card("In the distant future, historians will agree that _ marked the beginning of America's decline.", false));
        blackCards.add(new Card("What has been making life difficult at the nudist colony?", false));
        blackCards.add(new Card("And I would have gotten away with it, too, if it hadn't been for _.", false));
        blackCards.add(new Card("What brought the orgy to a grinding halt?", false));
        blackCards.add(new Card("During his midlife crisis, my dad got really into _.", false));
        blackCards.add(new Card("My new favorite porn star is Joey &#34;_&#34; McGee.", false));
        blackCards.add(new Card("Before I run for president, I must destroy all evidence of my involvement with _.", false));
        blackCards.add(new Card("This is your captain speaking. Fasten your seatbelts and prepare for _.", false));
        blackCards.add(new Card("In his newest and most difficult stunt, David Blaine must escape from _.", false));
        blackCards.add(new Card("The Five Stages of Grief: denial, anger, bargaining, _, and acceptance.", false));
        blackCards.add(new Card("Members of New York's social elite are paying thousands of dollars just to experience _.", false));
        blackCards.add(new Card("This month's Cosmo: Spice up your sex life by bringing _ into the bedroom.", false));
        blackCards.add(new Card("Little Miss Muffet Sat on a tuffet, Eating her curds and _.", false));
        blackCards.add(new Card("My country, 'tis of thee, sweet land of _.", false));
        blackCards.add(new Card("After months of debate, the Occupy Wall Street General Assembly could only agree on mpre _!", false));
        blackCards.add(new Card("Next time on Dr. Phil: How to talk to your child about _.", false));
        blackCards.add(new Card("Only two things in life are certain: death and _.", false));
        blackCards.add(new Card("Everyone down on the ground! We don't want to hurt anyone. We're just here for _.", false));
        blackCards.add(new Card("The healing process began when I joined a support group for victims of _.", false));
        blackCards.add(new Card("The votes are in, and the new high school mascot is _.", false));
        blackCards.add(new Card("Charades was ruined for me forever when my mom had to act out _.", false));
        blackCards.add(new Card("Tonight on 20/20: What you don't know about _ could kill you.", false));
        blackCards.add(new Card("D&D 4.0 isn't real D&D because of the _.", false));
        blackCards.add(new Card("It's a D&D retroclone with _ added.", false));
        blackCards.add(new Card("Storygames aren't RPGs because of the _.", false));
        blackCards.add(new Card("The Slayer's Guide to _.", false));
        blackCards.add(new Card("Alightment: Chaotic _", false));
        blackCards.add(new Card("It's a D&D retroclone with _ added.", false));
        blackCards.add(new Card("What made the paladin fall? _", false));
        blackCards.add(new Card("The portal leads to the quasi-elemental plane of _.", false));
        blackCards.add(new Card("The Temple of Elemental _.", false));
        blackCards.add(new Card("Pathfinder is basically D&D _ Edition.", false));
        blackCards.add(new Card("_ : The Storytelling Game.", false));
        blackCards.add(new Card("People are wondering why Steve Jackson published GURPS _.", false));
        blackCards.add(new Card("Linear Fighter, Quadratic _.", false));
        blackCards.add(new Card("You start with 1d4 _ points.", false));
        blackCards.add(new Card("Back when I was 12 and I was just starting playing D&D, the game had _.", false));
        blackCards.add(new Card("Big Eyes, Small _.", false));
        blackCards.add(new Card("In the grim darkness of the future there is only _.", false));
        blackCards.add(new Card("My innovative new RPG has a stat for _.", false));
        blackCards.add(new Card("A true gamer has no problem with _.", false));
        blackCards.add(new Card("The blackCards of Many _.", false));
        blackCards.add(new Card("You are all at a tavern when _ approach you.", false));
        blackCards.add(new Card("For the convention I cosplayed as Sailor Moon, except with _.", false));
        blackCards.add(new Card("The worst part of Grave of the Fireflies is all the _.", false));
        blackCards.add(new Card("In the Evangelion remake, Shinji has to deal with _.", false));
        blackCards.add(new Card("Worst anime convention purchase ever? _.", false));
        blackCards.add(new Card("While powering up Vegeta screamed, _!", false));
        blackCards.add(new Card("You evaded my _ attack. Most impressive.", false));
        blackCards.add(new Card("The magical girl found out that the Power of Love is useless against _.", false));
        blackCards.add(new Card("The Japanese government has spent billions of yen researching _.", false));
        blackCards.add(new Card("_ is Best Pony.", false));
        blackCards.add(new Card("The _ of Haruhi Suzumiya.", false));
        blackCards.add(new Card("The new thing in Akihabara is fetish cafes where you can see girls dressed up as _.", false));
        blackCards.add(new Card("Your drill can pierce _!", false));
        blackCards.add(new Card("Avatar: The Last _ bender.", false));
        blackCards.add(new Card("In the name of _ Sailor Moon will punish you!", false));
        blackCards.add(new Card("No harem anime is complete without _.", false));
        blackCards.add(new Card("My boyfriend's a _ now.", false));
        blackCards.add(new Card("_.tumblr.com", false));
        blackCards.add(new Card("Somehow they made a cute mascot girl out of _.", false));
        blackCards.add(new Card("Haruko hit Naoto in the head with her bass guitar and _ came out.", false));
        blackCards.add(new Card("After blacking out during New year's Eve, I was awoken by _.", false));
        blackCards.add(new Card("This holiday season, Tim Allen must overcome his fear of _ to save Christmas.", false));
        blackCards.add(new Card("Jesus is _.", false));
        blackCards.add(new Card("Every Christmas, my uncle gets drunk and tells the story about _.", false));
        blackCards.add(new Card("What keeps me warm during the cold, cold, winter?", false));
        blackCards.add(new Card("On the third day of Christmas, my true love gave to me: three French hens, two turtle doves, and _.", false));
        blackCards.add(new Card("Wake up, America. Christmas is under attack by secular liberals and their _.", false));
        blackCards.add(new Card("We got the third rope, now where's the fourth?", false));
        blackCards.add(new Card("Tackle, Dropdown, _.", false));
        blackCards.add(new Card("Christopher Daniels is late on his _.", false));
        blackCards.add(new Card("Genius is 10% inspiration, 90% _.", false));
        blackCards.add(new Card("The best thing I ever got for Christmas was _.", false));
        blackCards.add(new Card("There's no crying in _.", false));
        blackCards.add(new Card("Mastodon! Pterodactyl! Triceratops! Sabretooth Tiger! _!", false));
        blackCards.add(new Card("Don't eat the _.", false));
        blackCards.add(new Card("SOOOOO hot, want to touch the _.", false));
        blackCards.add(new Card("Stop looking at me _!", false));
        blackCards.add(new Card("I'm cuckoo for _ puffs.", false));
        blackCards.add(new Card("Silly rabbit, _ are for kids.", false));
        blackCards.add(new Card("Between love and madness lies _.", false));
        blackCards.add(new Card("Instead of chess, the Grim Reaper now gambles for your soul with a game of _.", false));
        blackCards.add(new Card("Why is my throat sore?", false));
        blackCards.add(new Card("I’m very sorry Mrs. Smith, but Little Billy has tested positive for _.", false));
        blackCards.add(new Card("Instead of beating them, Chris Brown now does _ to women.", false));
        blackCards.add(new Card("Instead of cutting, trendy young emo girls now engage in _.", false));
        blackCards.add(new Card("The definition of rock bottom is gambling away _.", false));
        blackCards.add(new Card("The Mayan prophecies really heralded the coming of _ in 2012.", false));
        blackCards.add(new Card("When I was 10 I wrote to Santa wishing for _.", false));
        blackCards.add(new Card("Where or How I met my last signifigant other: _.", false));
        blackCards.add(new Card("_, Never leave home without it.", false));
        blackCards.add(new Card("_. This is my fetish.", false));
        blackCards.add(new Card("I did _ so you don't have to!", false));
        blackCards.add(new Card("I need your clothes, your bike, and _.", false));
        blackCards.add(new Card("In a new Cold War retro movie, the red menace tries to conquer the world through the cunning use of _.", false));
        blackCards.add(new Card("My zombie survival kit includes food, water, and _.", false));
        blackCards.add(new Card("The way to a man's heart is through _.", false));
        blackCards.add(new Card("What was the theme of my second wedding?", false));
        blackCards.add(new Card("What's the newest Japanese craze to head West?", false));
        blackCards.add(new Card("Everybody loves _.", false));
        blackCards.add(new Card("I can only express myself through _.", false));
        blackCards.add(new Card("My new porn DVD was completely ruined by the inclusion of _", false));
        blackCards.add(new Card("The latest horrifying school shooting was inspired by _.", false));
        blackCards.add(new Card("I got fired because of my not-so-secret obsession over _.", false));
        blackCards.add(new Card("My new favourite sexual position is _", false));
        blackCards.add(new Card("A successful job interview begins with a firm handshake and ends with _.", false));
        blackCards.add(new Card("Lovin' you is easy 'cause you're _.", false));
        blackCards.add(new Card("The blind date was going horribly until we discovered our shared interest in _.", false));
        blackCards.add(new Card("_. Awesome in theory, kind of a mess in practice.", false));
        blackCards.add(new Card("I'm not like the rest of you. I'm too rich and busy for _.", false));
        blackCards.add(new Card("In the seventh circle of Hell, sinners must endure _ for all eternity.", false));
        blackCards.add(new Card("What left this stain on my couch?", false));
        blackCards.add(new Card("Call the law offices of Goldstein & Goldstein, because no one should have to tolerate _ in the workplace.", false));
        blackCards.add(new Card("Turns out that _-Man was neither the hero we needed nor wanted.", false));
        blackCards.add(new Card("As part of his daily regimen, Anderson Cooper sets aside 15 minutes for _.", false));
        blackCards.add(new Card("Money can't buy me love, but it can buy me _.", false));
        blackCards.add(new Card("And what did you bring for show and tell?", false));
        blackCards.add(new Card("During high school, I never really fit in until I found _ club.", false));
        blackCards.add(new Card("Hey, baby, come back to my place and I'll show you _.", false));
        blackCards.add(new Card("To prepare for his upcoming role, Daniel Day-Lewis immersed himself in the world of _.", false));
        blackCards.add(new Card("Finally! A service that delivers _ right to your door.", false));
        blackCards.add(new Card("My gym teacher got fired for adding _ to the obstacle course.", false));
        blackCards.add(new Card("As part of his contract, Prince won't perform without _ in his dressing room.", false));
        blackCards.add(new Card("It's only _ if you get caught!", false));
        blackCards.add(new Card("_: The Next Generation", false));
        blackCards.add(new Card("Terminator 4: _", false));
        blackCards.add(new Card("Disney presents _ on ice!", false));
        blackCards.add(new Card("_. The other white meat.", false));
        blackCards.add(new Card("I love the smell of _ in the morning.", false));
        blackCards.add(new Card("You're not gonna believe this, but _.", false));
        blackCards.add(new Card("_. All the cool kids are doing it.", false));
        blackCards.add(new Card("Baskin Robbins just added a 32nd flavor: _!", false));
        blackCards.add(new Card("I can drive and _ at the same time.", false));
        blackCards.add(new Card("_ ain't nothin' to fuck wit'!", false));
        i = 1;
        whiteCards.add(new Card("Flying sex snakes.", true));
        whiteCards.add(new Card("Michelle Obama's arms.", true));
        whiteCards.add(new Card("German dungeon porn.", true));
        whiteCards.add(new Card("White people.", true));
        whiteCards.add(new Card("Getting so angry that you pop a boner.", true));
        whiteCards.add(new Card("Tasteful sideboob.", true));
        whiteCards.add(new Card("Praying the gay away.", true));
        whiteCards.add(new Card("Two midgets shitting into a bucket.", true));
        whiteCards.add(new Card("MechaHitler.", true));
        whiteCards.add(new Card("Being a motherfucking sorcerer.", true));
        whiteCards.add(new Card("A disappointing birthday party.", true));
        whiteCards.add(new Card("Puppies!", true));
        whiteCards.add(new Card("A windmill full of corpses.", true));
        whiteCards.add(new Card("Guys who don't call.", true));
        whiteCards.add(new Card("Racially-biased SAT questions.", true));
        whiteCards.add(new Card("Dying.", true));
        whiteCards.add(new Card("Steven Hawking talking dirty.", true));
        whiteCards.add(new Card("Being on fire.", true));
        whiteCards.add(new Card("A lifetime of sadness.", true));
        whiteCards.add(new Card("An erection that lasts longer than four hours.", true));
        whiteCards.add(new Card("AIDS", true));
        whiteCards.add(new Card("Same-sex ice dancing.", true));
        whiteCards.add(new Card("Glenn Beck catching his scrotum on a curtain hook.", true));
        whiteCards.add(new Card("The Rapture.", true));
        whiteCards.add(new Card("Pterodactyl eggs.", true));
        whiteCards.add(new Card("Crippling debt.", true));
        whiteCards.add(new Card("Eugenics.", true));
        whiteCards.add(new Card("Exchanging pleasantries.", true));
        whiteCards.add(new Card("Dying of dysentery.", true));
        whiteCards.add(new Card("Roofies.", true));
        whiteCards.add(new Card("Getting naked and watching Nickelodeon.", true));
        whiteCards.add(new Card("The forbidden fruit.", true));
        whiteCards.add(new Card("Republicans.", true));
        whiteCards.add(new Card("The Big Bang.", true));
        whiteCards.add(new Card("Anal beads.", true));
        whiteCards.add(new Card("Amputees.", true));
        whiteCards.add(new Card("Men.", true));
        whiteCards.add(new Card("Surprise sex!", true));
        whiteCards.add(new Card("Kim Jong-il.", true));
        whiteCards.add(new Card("Concealing a boner", true));
        whiteCards.add(new Card("Agriculture.", true));
        whiteCards.add(new Card("Glenn Beck being harried by a swarm of buzzards.", true));
        whiteCards.add(new Card("Making a pouty face.", true));
        whiteCards.add(new Card("A salty surprise.", true));
        whiteCards.add(new Card("The Jews.", true));
        whiteCards.add(new Card("Charisma.", true));
        whiteCards.add(new Card("YOU MUST CONSTRUCT ADDITIONAL PYLONS.", true));
        whiteCards.add(new Card("Panda sex.", true));
        whiteCards.add(new Card("Taking off your shirt.", true));
        whiteCards.add(new Card("A drive-by shooting.", true));
        whiteCards.add(new Card("Ronald Reagan.", true));
        whiteCards.add(new Card("Morgan Freeman's voice.", true));
        whiteCards.add(new Card("Breaking out into song and dance.", true));
        whiteCards.add(new Card("Jewish fraternities.", true));
        whiteCards.add(new Card("Dead babies.", true));
        whiteCards.add(new Card("Masturbation.", true));
        whiteCards.add(new Card("Hormone injections.", true));
        whiteCards.add(new Card("All-you-can-eat shrimp for $4.99.", true));
        whiteCards.add(new Card("Incest.", true));
        whiteCards.add(new Card("Scalping.", true));
        whiteCards.add(new Card("Soup that is too hot.", true));
        whiteCards.add(new Card("The bermensch.", true));
        whiteCards.add(new Card("Nazis.", true));
        whiteCards.add(new Card("Tom Cruise.", true));
        whiteCards.add(new Card("Stifling a giggle at the mention of Hutus and Tutsis.", true));
        whiteCards.add(new Card("Edible underpants.", true));
        whiteCards.add(new Card("The Hustle.", true));
        whiteCards.add(new Card("A Super Soaker full of cat pee.", true));
        whiteCards.add(new Card("Figgy pudding.", true));
        whiteCards.add(new Card("Object permanence.", true));
        whiteCards.add(new Card("Consultants.", true));
        whiteCards.add(new Card("Intelligent design.", true));
        whiteCards.add(new Card("Nocturnal emissions.", true));
        whiteCards.add(new Card("Uppercuts.", true));
        whiteCards.add(new Card("Being marginalized.", true));
        whiteCards.add(new Card("The profoundly handicapped.", true));
        whiteCards.add(new Card("Obesity.", true));
        whiteCards.add(new Card("Chutzpah.", true));
        whiteCards.add(new Card("Unfathomable stupidity.", true));
        whiteCards.add(new Card("Repression.", true));
        whiteCards.add(new Card("Attitude.", true));
        whiteCards.add(new Card("Passable transvestites.", true));
        whiteCards.add(new Card("Party poopers.", true));
        whiteCards.add(new Card("The American Dream", true));
        whiteCards.add(new Card("Child beauty pageants.", true));
        whiteCards.add(new Card("Puberty.", true));
        whiteCards.add(new Card("Testicular torsion.", true));
        whiteCards.add(new Card("The folly of man.", true));
        whiteCards.add(new Card("Nickelback.", true));
        whiteCards.add(new Card("Swooping.", true));
        whiteCards.add(new Card("Goats eating cans.", true));
        whiteCards.add(new Card("The KKK.", true));
        whiteCards.add(new Card("Kamikaze pilots.", true));
        whiteCards.add(new Card("Horrifying laser hair removal accidents.", true));
        whiteCards.add(new Card("Adderall.", true));
        whiteCards.add(new Card("A look-see.", true));
        whiteCards.add(new Card("Doing the right thing.", true));
        whiteCards.add(new Card("The taint; the grundle; the fleshy fun-bridge.", true));
        whiteCards.add(new Card("Lactation.", true));
        whiteCards.add(new Card("Pabst Blue Ribbon.", true));
        whiteCards.add(new Card("Powerful thighs.", true));
        whiteCards.add(new Card("Saxophone solos.", true));
        whiteCards.add(new Card("The gays.", true));
        whiteCards.add(new Card("A middle-aged man on roller skates.", true));
        whiteCards.add(new Card("A foul mouth.", true));
        whiteCards.add(new Card("The thing that electrocutes your abs.", true));
        whiteCards.add(new Card("Heteronormativity.", true));
        whiteCards.add(new Card("Cuddling.", true));
        whiteCards.add(new Card("Coat hanger abortions.", true));
        whiteCards.add(new Card("A big hoopla about nothing.", true));
        whiteCards.add(new Card("Boogers.", true));
        whiteCards.add(new Card("A hot mess.", true));
        whiteCards.add(new Card("Raptor attacks.", true));
        whiteCards.add(new Card("My collection of high-tech sex toys.", true));
        whiteCards.add(new Card("Fear itself.", true));
        whiteCards.add(new Card("Bees?", true));
        whiteCards.add(new Card("Getting drunk on mouthwash.", true));
        whiteCards.add(new Card("Sniffing glue.", true));
        whiteCards.add(new Card("Oversized lollipops.", true));
        whiteCards.add(new Card("An icepick lobotomy.", true));
        whiteCards.add(new Card("Being rich.", true));
        whiteCards.add(new Card("Friends with benefits.", true));
        whiteCards.add(new Card("Teaching a robot to love.", true));
        whiteCards.add(new Card("Women's suffrage.", true));
        whiteCards.add(new Card("Me time.", true));
        whiteCards.add(new Card("The heart of a child.", true));
        whiteCards.add(new Card("Smallpox blankets.", true));
        whiteCards.add(new Card("The clitoris.", true));
        whiteCards.add(new Card("John Wilkes Booth.", true));
        whiteCards.add(new Card("The glass ceiling.", true));
        whiteCards.add(new Card("Sarah Palin.", true));
        whiteCards.add(new Card("Sexy pillow fights.", true));
        whiteCards.add(new Card("Yeast.", true));
        whiteCards.add(new Card("Full frontal nudity.", true));
        whiteCards.add(new Card("Parting the Red Sea.", true));
        whiteCards.add(new Card("A Bop It.", true));
        whiteCards.add(new Card("Michael Jackson.", true));
        whiteCards.add(new Card("Team-building exercises.", true));
        whiteCards.add(new Card("Harry Potter erotica.", true));
        whiteCards.add(new Card("Authentic Mexican cuisine.", true));
        whiteCards.add(new Card("Frolicking.", true));
        whiteCards.add(new Card("Sexting.", true));
        whiteCards.add(new Card("Grandma.", true));
        whiteCards.add(new Card("Not giving a shit about the Third World.", true));
        whiteCards.add(new Card("Licking things to claim them as your own.", true));
        whiteCards.add(new Card("Genghis Khan.", true));
        whiteCards.add(new Card("The hardworking Mexican.", true));
        whiteCards.add(new Card("RoboCop.", true));
        whiteCards.add(new Card("My relationship status.", true));
        whiteCards.add(new Card("Scrubbing under the folds.", true));
        whiteCards.add(new Card("Porn Stars.", true));
        whiteCards.add(new Card("Horse meat.", true));
        whiteCards.add(new Card("Sunshine and rainbows.", true));
        whiteCards.add(new Card("Expecting a burp and vomiting on the floor.", true));
        whiteCards.add(new Card("Barack Obama.", true));
        whiteCards.add(new Card("Spontaneous human combustion.", true));
        whiteCards.add(new Card("Natural selection.", true));
        whiteCards.add(new Card("Mouth herpes.", true));
        whiteCards.add(new Card("Flash flooding.", true));
        whiteCards.add(new Card("Goblins.", true));
        whiteCards.add(new Card("A monkey smoking a cigar.", true));
        whiteCards.add(new Card("Spectacular abs.", true));
        whiteCards.add(new Card("A good sniff.", true));
        whiteCards.add(new Card("Wiping her butt.", true));
        whiteCards.add(new Card("The Three-Fifths compromise.", true));
        whiteCards.add(new Card("Pedophiles.", true));
        whiteCards.add(new Card("Doin' it in the butt.", true));
        whiteCards.add(new Card("Being fabulous.", true));
        whiteCards.add(new Card("Mathletes.", true));
        whiteCards.add(new Card("Wearing underwear inside-out to avoid doing laundry.", true));
        whiteCards.add(new Card("Nipple blades.", true));
        whiteCards.add(new Card("An M. Night Shyamalan plot twist.", true));
        whiteCards.add(new Card("A bag of magic beans.", true));
        whiteCards.add(new Card("Vigorous jazz hands.", true));
        whiteCards.add(new Card("A defective condom.", true));
        whiteCards.add(new Card("Skeletor.", true));
        whiteCards.add(new Card("Vikings.", true));
        whiteCards.add(new Card("Leaving an awkward voicemail.", true));
        whiteCards.add(new Card("Teenage pregnancy.", true));
        whiteCards.add(new Card("Dead parents.", true));
        whiteCards.add(new Card("Hot cheese.", true));
        whiteCards.add(new Card("My sex life.", true));
        whiteCards.add(new Card("A mopey zoo lion.", true));
        whiteCards.add(new Card("Assless chaps.", true));
        whiteCards.add(new Card("Riding off into the sunset.", true));
        whiteCards.add(new Card("Lance Armstrong's missing testicle.", true));
        whiteCards.add(new Card("Sweet, sweet vengeance.", true));
        whiteCards.add(new Card("Genital piercings.", true));
        whiteCards.add(new Card("Keg stands.", true));
        whiteCards.add(new Card("Darth Vader.", true));
        whiteCards.add(new Card("Viagra.", true));
        whiteCards.add(new Card("Necrophilia.", true));
        whiteCards.add(new Card("A really cool hat.", true));
        whiteCards.add(new Card("Toni Morrison's vagina.", true));
        whiteCards.add(new Card("An Oedipus complex.", true));
        whiteCards.add(new Card("The Tempur-Pedic Swedish Sleep System.", true));
        whiteCards.add(new Card("Preteens.", true));
        whiteCards.add(new Card("Dick fingers.", true));
        whiteCards.add(new Card("A cooler full of organs.", true));
        whiteCards.add(new Card("Shapeshifters.", true));
        whiteCards.add(new Card("The Care Bear Stare.", true));
        whiteCards.add(new Card("Erectile dysfunction.", true));
        whiteCards.add(new Card("Keanu Reeves.", true));
        whiteCards.add(new Card("The Virginia Tech Massacre.", true));
        whiteCards.add(new Card("The Underground Railroad.", true));
        whiteCards.add(new Card("The chronic.", true));
        whiteCards.add(new Card("Queefing.", true));
        whiteCards.add(new Card("Heartwarming orphans.", true));
        whiteCards.add(new Card("A thermonuclear detonation.", true));
        whiteCards.add(new Card("Cheating in the Special Olympics.", true));
        whiteCards.add(new Card("Tangled Slinkys.", true));
        whiteCards.add(new Card("A moment of silence.", true));
        whiteCards.add(new Card("Civilian casualties.", true));
        whiteCards.add(new Card("Catapults.", true));
        whiteCards.add(new Card("Sharing needles.", true));
        whiteCards.add(new Card("Ethnic cleansing.", true));
        whiteCards.add(new Card("Emotions.", true));
        whiteCards.add(new Card("Children on leashes.", true));
        whiteCards.add(new Card("Balls.", true));
        whiteCards.add(new Card("Homeless people.", true));
        whiteCards.add(new Card("Eating all of the cookies before the AIDS bake-sale.", true));
        whiteCards.add(new Card("Old-people smell.", true));
        whiteCards.add(new Card("Farting and walking away.", true));
        whiteCards.add(new Card("The inevitable heat death of the universe.", true));
        whiteCards.add(new Card("The violation of our most basic human rights.", true));
        whiteCards.add(new Card("Fingering.", true));
        whiteCards.add(new Card("The placenta.", true));
        whiteCards.add(new Card("The Rev. Dr. Martin Luther King, Jr.", true));
        whiteCards.add(new Card("Leprosy.", true));
        whiteCards.add(new Card("Sperm whales.", true));
        whiteCards.add(new Card("Multiple stab wounds.", true));
        whiteCards.add(new Card("Flightless birds.", true));
        whiteCards.add(new Card("Grave robbing.", true));
        whiteCards.add(new Card("Home video of Oprah sobbing into a Lean Cuisine.", true));
        whiteCards.add(new Card("Oompa-Loompas.", true));
        whiteCards.add(new Card("A murder most foul.", true));
        whiteCards.add(new Card("Tentacle porn.", true));
        whiteCards.add(new Card("Daddy issues.", true));
        whiteCards.add(new Card("Bill Nye the Science Guy.", true));
        whiteCards.add(new Card("Peeing a little bit.", true));
        whiteCards.add(new Card("The miracle of childbirth.", true));
        whiteCards.add(new Card("Tweeting.", true));
        whiteCards.add(new Card("Another goddamn vampire movie.", true));
        whiteCards.add(new Card("Britney Spears at 55.", true));
        whiteCards.add(new Card("New Age music.", true));
        whiteCards.add(new Card("The Make-A-Wish Foundation.", true));
        whiteCards.add(new Card("Firing a rifle into the air while balls deep in a squealing hog.", true));
        whiteCards.add(new Card("Active listening.", true));
        whiteCards.add(new Card("Nicolas Cage.", true));
        whiteCards.add(new Card("72 virgins.", true));
        whiteCards.add(new Card("Rtranger danger.", true));
        whiteCards.add(new Card("Hope.", true));
        whiteCards.add(new Card("A gassy antelope.", true));
        whiteCards.add(new Card("BATMAN!!!", true));
        whiteCards.add(new Card("Chivalry.", true));
        whiteCards.add(new Card("Passing a kidney stone.", true));
        whiteCards.add(new Card("Black people.", true));
        whiteCards.add(new Card("Natalie Portman.", true));
        whiteCards.add(new Card("A mime having a stroke.", true));
        whiteCards.add(new Card("Classist undertones.", true));
        whiteCards.add(new Card("Rean Penn.", true));
        whiteCards.add(new Card("A mating display.", true));
        whiteCards.add(new Card("The Holy Bible.", true));
        whiteCards.add(new Card("Hot Pockets.", true));
        whiteCards.add(new Card("A sad handjob.", true));
        whiteCards.add(new Card("Pulling out.", true));
        whiteCards.add(new Card("Rerfdom.", true));
        whiteCards.add(new Card("Pixelated bukkake.", true));
        whiteCards.add(new Card("Dropping a chandelier on your enemies and riding the rope up.", true));
        whiteCards.add(new Card("Jew-fros.", true));
        whiteCards.add(new Card("Waiting 'til marriage.", true));
        whiteCards.add(new Card("Euphoria by Calvin Klein.", true));
        whiteCards.add(new Card("The World of Warcraft.", true));
        whiteCards.add(new Card("Lunchables.", true));
        whiteCards.add(new Card("The Kool-Aid Man.", true));
        whiteCards.add(new Card("The Trail of Tears.", true));
        whiteCards.add(new Card("Relf-loathing.", true));
        whiteCards.add(new Card("A falcon with a cap on its head.", true));
        whiteCards.add(new Card("Historically black colleges.", true));
        whiteCards.add(new Card("Not reciprocating oral sex.", true));
        whiteCards.add(new Card("Global warming.", true));
        whiteCards.add(new Card("Ghosts.", true));
        whiteCards.add(new Card("World peace.", true));
        whiteCards.add(new Card("A can of whoop-ass.", true));
        whiteCards.add(new Card("The Dance of the Sugar Plum Fairy.", true));
        whiteCards.add(new Card("A zesty breakfast burrito.", true));
        whiteCards.add(new Card("Rwitching to Geico.", true));
        whiteCards.add(new Card("Aaron Burr.", true));
        whiteCards.add(new Card("Picking up girls at the abortion clinic.", true));
        whiteCards.add(new Card("Land mines.", true));
        whiteCards.add(new Card("Former President George W. Bush.", true));
        whiteCards.add(new Card("Geese.", true));
        whiteCards.add(new Card("Mutually-assured destruction.", true));
        whiteCards.add(new Card("College.", true));
        whiteCards.add(new Card("Date rape.", true));
        whiteCards.add(new Card("Bling.", true));
        whiteCards.add(new Card("A gentle caress of the inner thigh.", true));
        whiteCards.add(new Card("A time travel paradox.", true));
        whiteCards.add(new Card("Reppuku.", true));
        whiteCards.add(new Card("Poor life choices.", true));
        whiteCards.add(new Card("Waking up half-naked in a Denny's parking lot.", true));
        whiteCards.add(new Card("Italians.", true));
        whiteCards.add(new Card("GoGurt.", true));
        whiteCards.add(new Card("Finger painting.", true));
        whiteCards.add(new Card("Robert Downey, Jr.", true));
        whiteCards.add(new Card("My soul.", true));
        whiteCards.add(new Card("Rmegma.", true));
        whiteCards.add(new Card("Embryonic stem cells.", true));
        whiteCards.add(new Card("The South.", true));
        whiteCards.add(new Card("Christopher Walken.", true));
        whiteCards.add(new Card("Gloryholes.", true));
        whiteCards.add(new Card("Pretending to care.", true));
        whiteCards.add(new Card("Public ridicule.", true));
        whiteCards.add(new Card("A tiny horse.", true));
        whiteCards.add(new Card("Arnold Schwarzenegger.", true));
        whiteCards.add(new Card("A stray pube.", true));
        whiteCards.add(new Card("Jerking off into a pool of children's tears.", true));
        whiteCards.add(new Card("Child abuse.", true));
        whiteCards.add(new Card("Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.", true));
        whiteCards.add(new Card("Menstruation.", true));
        whiteCards.add(new Card("A sassy black woman.", true));
        whiteCards.add(new Card("Re-gifting.", true));
        whiteCards.add(new Card("Penis envy.", true));
        whiteCards.add(new Card("A sausage festival.", true));
        whiteCards.add(new Card("Getting really high.", true));
        whiteCards.add(new Card("Drinking alone.", true));
        whiteCards.add(new Card("Too much hair gel.", true));
        whiteCards.add(new Card("Hulk Hogan.", true));
        whiteCards.add(new Card("Overcompensation.", true));
        whiteCards.add(new Card("Foreskin.", true));
        whiteCards.add(new Card("Free samples.", true));
        whiteCards.add(new Card("Rhaquille O'Neal's acting career.", true));
        whiteCards.add(new Card("Five-Dollar Footlongs.", true));
        whiteCards.add(new Card("Whipping it out.", true));
        whiteCards.add(new Card("A snapping turtle biting the tip of your penis.", true));
        whiteCards.add(new Card("Muhammad (Praise Be Unto Him, true)).", true));
        whiteCards.add(new Card("Half-assed foreplay.", true));
        whiteCards.add(new Card("Dental dams.", true));
        whiteCards.add(new Card("Being a dick to children.", true));
        whiteCards.add(new Card("Famine.", true));
        whiteCards.add(new Card("Chainsaws for hands.", true));
        whiteCards.add(new Card("A gypsy curse.", true));
        whiteCards.add(new Card("AXE Body Spray.", true));
        whiteCards.add(new Card("The Force.", true));
        whiteCards.add(new Card("Explosions.", true));
        whiteCards.add(new Card("Cybernetic enhancements.", true));
        whiteCards.add(new Card("Customer service representatives.", true));
        whiteCards.add(new Card("White privilege.", true));
        whiteCards.add(new Card("Gandhi.", true));
        whiteCards.add(new Card("Road head.", true));
        whiteCards.add(new Card("God.", true));
        whiteCards.add(new Card("Poorly-timed Holocaust jokes.", true));
        whiteCards.add(new Card("8 oz. of sweet Mexican black-tar heroin.", true));
        whiteCards.add(new Card("Judge Judy.", true));
        whiteCards.add(new Card("The Little Engine That Could.", true));
        whiteCards.add(new Card("Altar boys.", true));
        whiteCards.add(new Card("Mr. Clean, right behind you.", true));
        whiteCards.add(new Card("Vehicular manslaughter.", true));
        whiteCards.add(new Card("Dwarf tossing.", true));
        whiteCards.add(new Card("Friction.", true));
        whiteCards.add(new Card("Lady Gaga.", true));
        whiteCards.add(new Card("Rcientology.", true));
        whiteCards.add(new Card("Justin Bieber.", true));
        whiteCards.add(new Card("A death ray.", true));
        whiteCards.add(new Card("Vigilante justice.", true));
        whiteCards.add(new Card("The Pope.", true));
        whiteCards.add(new Card("A sea of troubles.", true));
        whiteCards.add(new Card("Alcoholism.", true));
        whiteCards.add(new Card("Poor people.", true));
        whiteCards.add(new Card("A fetus.", true));
        whiteCards.add(new Card("Women in yogurt commercials.", true));
        whiteCards.add(new Card("Exactly what you'd expect.", true));
        whiteCards.add(new Card("Flesh-eating bacteria.", true));
        whiteCards.add(new Card("My genitals.", true));
        whiteCards.add(new Card("A balanced breakfast.", true));
        whiteCards.add(new Card("Dick Cheney.", true));
        whiteCards.add(new Card("Lockjaw.", true));
        whiteCards.add(new Card("Natural male enhancement.", true));
        whiteCards.add(new Card("Take-backsies.", true));
        whiteCards.add(new Card("Winking at old people.", true));
        whiteCards.add(new Card("Opposable thumbs.", true));
        whiteCards.add(new Card("Flying sex snakes.", true));
        whiteCards.add(new Card("Passive-aggressive Post-it notes.", true));
        whiteCards.add(new Card("Inappropriate yodeling.", true));
        whiteCards.add(new Card("Golden showers.", true));
        whiteCards.add(new Card("Racism.", true));
        whiteCards.add(new Card("Copping a feel.", true));
        whiteCards.add(new Card("Auschwitz.", true));
        whiteCards.add(new Card("Elderly Japanese men.", true));
        whiteCards.add(new Card("Raping and pillaging.", true));
        whiteCards.add(new Card("Kids with ass cancer.", true));
        whiteCards.add(new Card("Pictures of boobs.", true));
        whiteCards.add(new Card("The homosexual agenda.", true));
        whiteCards.add(new Card("A homoerotic volleyball montage.", true));
        whiteCards.add(new Card("Sexual tension.", true));
        whiteCards.add(new Card("Hurricane Katrina.", true));
        whiteCards.add(new Card("Fiery poops.", true));
        whiteCards.add(new Card("Science.", true));
        whiteCards.add(new Card("Dry heaving.", true));
        whiteCards.add(new Card("Cards Against Humanity.", true));
        whiteCards.add(new Card("Fancy Feast.", true));
        whiteCards.add(new Card("A bleached asshole.", true));
        whiteCards.add(new Card("Lumberjack fantasies.", true));
        whiteCards.add(new Card("American Gladiators.", true));
        whiteCards.add(new Card("Autocannibalism.", true));
        whiteCards.add(new Card("Sean Connery.", true));
        whiteCards.add(new Card("William Shatner.", true));
        whiteCards.add(new Card("Domino's Oreo Dessert Pizza.", true));
        whiteCards.add(new Card("An asymmetric boob job.", true));
        whiteCards.add(new Card("Centaurs.", true));
        whiteCards.add(new Card("A micropenis.", true));
        whiteCards.add(new Card("Asians who aren't good at math.", true));
        whiteCards.add(new Card("The milk man.", true));
        whiteCards.add(new Card("Waterboarding.", true));
        whiteCards.add(new Card("Wifely duties.", true));
        whiteCards.add(new Card("Loose lips.", true));
        whiteCards.add(new Card("The Blood of Christ.", true));
        whiteCards.add(new Card("Actually taking candy from a baby.", true));
        whiteCards.add(new Card("The token minority.", true));
        whiteCards.add(new Card("Jibber-jabber.", true));
        whiteCards.add(new Card("A brain tumor.", true));
        whiteCards.add(new Card("Bingeing and purging.", true));
        whiteCards.add(new Card("A clandestine butt scratch.", true));
        whiteCards.add(new Card("The Chinese gymnastics team.", true));
        whiteCards.add(new Card("Prancing.", true));
        whiteCards.add(new Card("The Hamburglar.", true));
        whiteCards.add(new Card("Police brutality.", true));
        whiteCards.add(new Card("Man meat.", true));
        whiteCards.add(new Card("Forgetting the Alamo.", true));
        whiteCards.add(new Card("Eating the last known bison.", true));
        whiteCards.add(new Card("Crystal meth.", true));
        whiteCards.add(new Card("Booby-trapping the house to foil burglars.", true));
        whiteCards.add(new Card("My inner demons.", true));
        whiteCards.add(new Card("Third base.", true));
        whiteCards.add(new Card("Soiling oneself.", true));
        whiteCards.add(new Card("Laying an egg.", true));
        whiteCards.add(new Card("Giving 110%.", true));
        whiteCards.add(new Card("Hot people.", true));
        whiteCards.add(new Card("Friendly fire.", true));
        whiteCards.add(new Card("Count Chocula.", true));
        whiteCards.add(new Card("Pac-Man uncontrollably guzzling cum.", true));
        whiteCards.add(new Card("Estrogen.", true));
        whiteCards.add(new Card("My vagina.", true));
        whiteCards.add(new Card("Kanye West.", true));
        whiteCards.add(new Card("A robust mongoloid.", true));
        whiteCards.add(new Card("The Donald Trump Seal of Approval.", true));
        whiteCards.add(new Card("The true meaning of Christmas.", true));
        whiteCards.add(new Card("Her Royal Highness, Queen Elizabeth II.", true));
        whiteCards.add(new Card("An honest cop with nothing left to lose.", true));
        whiteCards.add(new Card("Feeding Rosie O'Donnell.", true));
        whiteCards.add(new Card("The Amish.", true));
        whiteCards.add(new Card("The terrorists.", true));
        whiteCards.add(new Card("When you fart and a little bit comes out.", true));
        whiteCards.add(new Card("Pooping back and forth. Forever.", true));
        whiteCards.add(new Card("Friends who eat all the snacks.", true));
        whiteCards.add(new Card("Cockfights.", true));
        whiteCards.add(new Card("Bitches.", true));
        whiteCards.add(new Card("Seduction.", true));
        whiteCards.add(new Card("A big black dick.", true));
        whiteCards.add(new Card("A beached whale.", true));
        whiteCards.add(new Card("A bloody pacifier.", true));
        whiteCards.add(new Card("A crappy little hand.", true));
        whiteCards.add(new Card("A low standard of living.", true));
        whiteCards.add(new Card("A nuanced critique.", true));
        whiteCards.add(new Card("Panty raids.", true));
        whiteCards.add(new Card("A passionate Latino lover.", true));
        whiteCards.add(new Card("A rival dojo.", true));
        whiteCards.add(new Card("A web of lies.", true));
        whiteCards.add(new Card("A woman scorned.", true));
        whiteCards.add(new Card("Clams.", true));
        whiteCards.add(new Card("Apologizing.", true));
        whiteCards.add(new Card("A plunger to the face.", true));
        whiteCards.add(new Card("Neil Patrick Harris.", true));
        whiteCards.add(new Card("Beating your wives.", true));
        whiteCards.add(new Card("Being a dinosaur.", true));
        whiteCards.add(new Card("Shaft.", true));
        whiteCards.add(new Card("Bosnian chicken farmers.", true));
        whiteCards.add(new Card("Nubile slave boys.", true));
        whiteCards.add(new Card("Carnies.", true));
        whiteCards.add(new Card("Coughing into a vagina.", true));
        whiteCards.add(new Card("Suicidal thoughts.", true));
        whiteCards.add(new Card("The ooze.", true));
        whiteCards.add(new Card("Deflowering the princess.", true));
        whiteCards.add(new Card("Dorito breath.", true));
        whiteCards.add(new Card("Eating an albino.", true));
        whiteCards.add(new Card("Enormous Scandinavian women.", true));
        whiteCards.add(new Card("Fabricating statistics.", true));
        whiteCards.add(new Card("Finding a skeleton.", true));
        whiteCards.add(new Card("Gandalf.", true));
        whiteCards.add(new Card("Genetically engineered super-soldiers.", true));
        whiteCards.add(new Card("George Clooney's musk.", true));
        whiteCards.add(new Card("Getting abducted by Peter Pan.", true));
        whiteCards.add(new Card("Getting in her pants, politely.", true));
        whiteCards.add(new Card("Gladiatorial combat.", true));
        whiteCards.add(new Card("Clenched butt cheeks.", true));
        whiteCards.add(new Card("Hipsters.", true));
        whiteCards.add(new Card("Historical revisionism.", true));
        whiteCards.add(new Card("Insatiable bloodlust.", true));
        whiteCards.add(new Card("Jafar.", true));
        whiteCards.add(new Card("Jean-Claude Van Damme.", true));
        whiteCards.add(new Card("Just the tip.", true));
        whiteCards.add(new Card("Mad hacky-sack skills.", true));
        whiteCards.add(new Card("Leveling up.", true));
        whiteCards.add(new Card("Literally eating shit.", true));
        whiteCards.add(new Card("Making the penises kiss.", true));
        whiteCards.add(new Card("24-hour media coverage.", true));
        whiteCards.add(new Card("Medieval Times Dinner & Tournament.", true));
        whiteCards.add(new Card("Moral ambiguity.", true));
        whiteCards.add(new Card("My machete.", true));
        whiteCards.add(new Card("One thousand Slim Jims.", true));
        whiteCards.add(new Card("Ominous background music.", true));
        whiteCards.add(new Card("Overpowering your father.", true));
        whiteCards.add(new Card("Stockholm Syndrome.", true));
        whiteCards.add(new Card("Quiche.", true));
        whiteCards.add(new Card("Quivering jowls.", true));
        whiteCards.add(new Card("Revenge fucking.", true));
        whiteCards.add(new Card("Ripping into a man's chest and pulling out his still-beating heart.", true));
        whiteCards.add(new Card("Ryan Gosling riding in on a white horse.", true));
        whiteCards.add(new Card("Santa Claus.", true));
        whiteCards.add(new Card("Scrotum tickling.", true));
        whiteCards.add(new Card("Sexual humiliation.", true));
        whiteCards.add(new Card("Sexy Siamese twins.", true));
        whiteCards.add(new Card("Saliva.", true));
        whiteCards.add(new Card("Space muffins.", true));
        whiteCards.add(new Card("Statistically validated stereotypes.", true));
        whiteCards.add(new Card("Sudden Poop Explosion Disease.", true));
        whiteCards.add(new Card("The boners of the elderly.", true));
        whiteCards.add(new Card("The economy.", true));
        whiteCards.add(new Card("Syphilitic insanity.", true));
        whiteCards.add(new Card("The Gulags.", true));
        whiteCards.add(new Card("The harsh light of day.", true));
        whiteCards.add(new Card("The hiccups.", true));
        whiteCards.add(new Card("The shambling corpse of Larry King.", true));
        whiteCards.add(new Card("The four arms of Vishnu.", true));
        whiteCards.add(new Card("Being a busy adult with many important things to do.", true));
        whiteCards.add(new Card("Tripping balls.", true));
        whiteCards.add(new Card("Words, words, words.", true));
        whiteCards.add(new Card("Zeus's sexual appetites.", true));
        whiteCards.add(new Card("A bigger, blacker dick.", true));
        whiteCards.add(new Card("The mere concept of Applebee's.", true));
        whiteCards.add(new Card("A sad fat dragon with no friends.", true));
        whiteCards.add(new Card("Catastrophic urethral trauma.", true));
        whiteCards.add(new Card("Hillary Clinton's death stare.", true));
        whiteCards.add(new Card("Existing.", true));
        whiteCards.add(new Card("A pinata full of scorpions.", true));
        whiteCards.add(new Card("Mooing.", true));
        whiteCards.add(new Card("Swiftly achieving orgasm.", true));
        whiteCards.add(new Card("Daddy's belt.", true));
        whiteCards.add(new Card("Double penetration.", true));
        whiteCards.add(new Card("Weapons-grade plutonium.", true));
        whiteCards.add(new Card("Some really fucked-up shit.", true));
        whiteCards.add(new Card("Subduing a grizzly bear and making her your wife.", true));
        whiteCards.add(new Card("Rising from the grave.", true));
        whiteCards.add(new Card("The mixing of the races.", true));
        whiteCards.add(new Card("Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.", true));
        whiteCards.add(new Card("Scrotal frostbite.", true));
        whiteCards.add(new Card("All of this blood.", true));
        whiteCards.add(new Card("Loki, the trickster god.", true));
        whiteCards.add(new Card("Whining like a little bitch.", true));
        whiteCards.add(new Card("Pumping out a baby every nine months.", true));
        whiteCards.add(new Card("Tongue.", true));
        whiteCards.add(new Card("Finding Waldo.", true));
        whiteCards.add(new Card("Upgrading homeless people to mobile hotspots.", true));
        whiteCards.add(new Card("Wearing an octopus for a hat.", true));
        whiteCards.add(new Card("An unhinged ferris wheel rolling toward the sea.", true));
        whiteCards.add(new Card("Living in a trashcan.", true));
        whiteCards.add(new Card("The corporations.", true));
        whiteCards.add(new Card("A magic hippie love cloud.", true));
        whiteCards.add(new Card("Fuck Mountain.", true));
        whiteCards.add(new Card("Survivor's guilt.", true));
        whiteCards.add(new Card("Me.", true));
        whiteCards.add(new Card("Getting hilariously gang-banged by the Blue Man Group.", true));
        whiteCards.add(new Card("Jeff Goldblum.", true));
        whiteCards.add(new Card("Making a friend.", true));
        whiteCards.add(new Card("A soulful rendition of Ol' Man River.", true));
        whiteCards.add(new Card("Intimacy problems.", true));
        whiteCards.add(new Card("A sweaty, panting leather daddy.", true));
        whiteCards.add(new Card("Spring break!", true));
        whiteCards.add(new Card("Being awesome at sex.", true));
        whiteCards.add(new Card("Dining with cardboard cutouts of the cast of Friends.", true));
        whiteCards.add(new Card("Another shot of morphine.", true));
        whiteCards.add(new Card("Beefin' over turf.", true));
        whiteCards.add(new Card("A squadron of moles wearing aviator goggles.", true));
        whiteCards.add(new Card("Bullshit.", true));
        whiteCards.add(new Card("The Google.", true));
        whiteCards.add(new Card("Pretty Pretty Princess Dress-Up Board Game.", true));
        whiteCards.add(new Card("The new Radiohead album.", true));
        whiteCards.add(new Card("An army of skeletons.", true));
        whiteCards.add(new Card("A man in yoga pants with a ponytail and feather earrings.", true));
        whiteCards.add(new Card("Mild autism.", true));
        whiteCards.add(new Card("Nunchuck moves.", true));
        whiteCards.add(new Card("Whipping a disobedient slave.", true));
        whiteCards.add(new Card("An ether-soaked rag.", true));
        whiteCards.add(new Card("A sweet spaceship.", true));
        whiteCards.add(new Card("A 55-gallon drum of lube.", true));
        whiteCards.add(new Card("Special musical guest, Cher.", true));
        whiteCards.add(new Card("The human body.", true));
        whiteCards.add(new Card("Boris the Soviet Love Hammer.", true));
        whiteCards.add(new Card("The grey nutrient broth that sustains Mitt Romney.", true));
        whiteCards.add(new Card("Tiny nipples.", true));
        whiteCards.add(new Card("Power.", true));
        whiteCards.add(new Card("Oncoming traffic.", true));
        whiteCards.add(new Card("A dollop of sour cream.", true));
        whiteCards.add(new Card("A slightly shittier parallel universe.", true));
        whiteCards.add(new Card("My first kill.", true));
        whiteCards.add(new Card("Graphic violence, adult language, and some sexual content.", true));
        whiteCards.add(new Card("Fetal alcohol syndrome.", true));
        whiteCards.add(new Card("The day the birds attacked.", true));
        whiteCards.add(new Card("One Ring to rule them all.", true));
        whiteCards.add(new Card("Grandpa's ashes.", true));
        whiteCards.add(new Card("Basic human decency.", true));
        whiteCards.add(new Card("A Burmese tiger pit.", true));
        whiteCards.add(new Card("Death by Steven Seagal", true));
        whiteCards.add(new Card("Dragon boobs.", true));
        whiteCards.add(new Card("Verisimilitude.", true));
        whiteCards.add(new Card("Dissociated mechanics.", true));
        whiteCards.add(new Card("Rape.", true));
        whiteCards.add(new Card("Storygames.", true));
        whiteCards.add(new Card("Random chargen", true));
        whiteCards.add(new Card("RPG.net.", true));
        whiteCards.add(new Card("Dice inserted somewhere painful.", true));
        whiteCards.add(new Card("FATAL.", true));
        whiteCards.add(new Card("Ron Edwards' brain damage.", true));
        whiteCards.add(new Card("Boob plate armor.", true));
        whiteCards.add(new Card("Gamer chicks.", true));
        whiteCards.add(new Card("FNS theory.", true));
        whiteCards.add(new Card("Drizzt.", true));
        whiteCards.add(new Card("The entire Palladium Books Megaverse", true));
        whiteCards.add(new Card("BadWrongFun.", true));
        whiteCards.add(new Card("Misogynerds.", true));
        whiteCards.add(new Card("Cultural Marxism.", true));
        whiteCards.add(new Card("Pissing on Gary Gygax's grave.", true));
        whiteCards.add(new Card("Steve Jackson's beard.", true));
        whiteCards.add(new Card("Natural 20.", true));
        whiteCards.add(new Card("Rapenards.", true));
        whiteCards.add(new Card("The Crisis of Treachery.", true));
        whiteCards.add(new Card("Fame balance.", true));
        whiteCards.add(new Card("Fishmalks.", true));
        whiteCards.add(new Card("A kick to the dicebags.", true));
        whiteCards.add(new Card("Bearded dwarven women.", true));
        whiteCards.add(new Card("Owlbear's tears.", true));
        whiteCards.add(new Card("Magic missile.", true));
        whiteCards.add(new Card("THAC0.", true));
        whiteCards.add(new Card("Bigby's Groping Hands.", true));
        whiteCards.add(new Card("Drow blackface.", true));
        whiteCards.add(new Card("Save or die.", true));
        whiteCards.add(new Card("Swine.", true));
        whiteCards.add(new Card("The Forge.", true));
        whiteCards.add(new Card("Healing Surges.", true));
        whiteCards.add(new Card("Felatinous Cubes.", true));
        whiteCards.add(new Card("Total Party Kill.", true));
        whiteCards.add(new Card("Quoting Monty Python.", true));
        whiteCards.add(new Card("Dumbed down shit for ADD WoW babies.", true));
        whiteCards.add(new Card("Mike Mearls.", true));
        whiteCards.add(new Card("Comeliness.", true));
        whiteCards.add(new Card("Vampire: The Masquerade.", true));
        whiteCards.add(new Card("Rifts.", true));
        whiteCards.add(new Card("The random prostitute table.", true));
        whiteCards.add(new Card("Dildo of Enlightenment +2", true));
        whiteCards.add(new Card("Frognards Against Humanity.", true));
        whiteCards.add(new Card("Cthulhu.", true));
        whiteCards.add(new Card("The naked succubus in the Monster Manual.", true));
        whiteCards.add(new Card("Role-playing and roll-playing.", true));
        whiteCards.add(new Card("Fun Tyrant.", true));
        whiteCards.add(new Card("4rries.", true));
        whiteCards.add(new Card("Martial dailies.", true));
        whiteCards.add(new Card("Black Tokyo.", true));
        whiteCards.add(new Card("Killfuck Soulshitter.", true));
        whiteCards.add(new Card("Cheetoism.", true));
        whiteCards.add(new Card("Frimdark.", true));
        whiteCards.add(new Card("Kobolds.", true));
        whiteCards.add(new Card("Oozemaster.", true));
        whiteCards.add(new Card("Rocks fall, everyone dies.", true));
        whiteCards.add(new Card("Mark ReinHagen.", true));
        whiteCards.add(new Card("Maid RPG.", true));
        whiteCards.add(new Card("Splugorth blind warrior women.", true));
        whiteCards.add(new Card("Dying during chargen.", true));
        whiteCards.add(new Card("Slaughtering innocent orc children.", true));
        whiteCards.add(new Card("Lesbian stripper ninjas.", true));
        whiteCards.add(new Card("Magical tea party.", true));
        whiteCards.add(new Card("Frinding levels.", true));
        whiteCards.add(new Card("Dice animism.", true));
        whiteCards.add(new Card("White privilege.", true));
        whiteCards.add(new Card("Fithyanki therapy.", true));
        whiteCards.add(new Card("Amber Diceless Roleplaying.", true));
        whiteCards.add(new Card("A ratcatcher with a small but vicious dog.", true));
        whiteCards.add(new Card("Bribing the GM with sexual favors.", true));
        whiteCards.add(new Card("Eurocentric fantasy.", true));
        whiteCards.add(new Card("Sacred cows.", true));
        whiteCards.add(new Card("Fygaxian naturalism.", true));
        whiteCards.add(new Card("Special snowflakes.", true));
        whiteCards.add(new Card("Neckbeards.", true));
        whiteCards.add(new Card("Fazebos.", true));
        whiteCards.add(new Card("Lorraine Williams.", true));
        whiteCards.add(new Card("Nude larping.", true));
        whiteCards.add(new Card("Portable holes.", true));
        whiteCards.add(new Card("Steampunk bullshit.", true));
        whiteCards.add(new Card("Dump stats.", true));
        whiteCards.add(new Card("Ale and whores.", true));
        whiteCards.add(new Card("Japanese schoolgirl porn.", true));
        whiteCards.add(new Card("Horny catgirls.", true));
        whiteCards.add(new Card("Japanese people.", true));
        whiteCards.add(new Card("Cimo.", true));
        whiteCards.add(new Card("ZA WARUDO!", true));
        whiteCards.add(new Card("40 gigs of lolicon.", true));
        whiteCards.add(new Card("Foku's hair.", true));
        whiteCards.add(new Card("Slashfic.", true));
        whiteCards.add(new Card("Star Gentle Uterus", true));
        whiteCards.add(new Card("Naruto headbands.", true));
        whiteCards.add(new Card("Homestuck troll horns.", true));
        whiteCards.add(new Card("Hayao Miyazaki.", true));
        whiteCards.add(new Card("The tsunami.", true));
        whiteCards.add(new Card("Death Note.", true));
        whiteCards.add(new Card("Small breasts.", true));
        whiteCards.add(new Card("Asians being racist against each other.", true));
        whiteCards.add(new Card("Weeaboo bullshit.", true));
        whiteCards.add(new Card("Tsundere.", true));
        whiteCards.add(new Card("Body pillows.", true));
        whiteCards.add(new Card("A lifelike silicone love doll.", true));
        whiteCards.add(new Card("Anime figures drenched in jizz.", true));
        whiteCards.add(new Card("Surprise sex.", true));
        whiteCards.add(new Card("Yaoi.", true));
        whiteCards.add(new Card("Firls with glasses.", true));
        whiteCards.add(new Card("Bronies.", true));
        whiteCards.add(new Card("Blue and white striped panties.", true));
        whiteCards.add(new Card("4chan.", true));
        whiteCards.add(new Card("Hello Kitty vibrator.", true));
        whiteCards.add(new Card("Finishing attack.", true));
        whiteCards.add(new Card("Keikaku* *(keikaku means plan, true)).", true));
        whiteCards.add(new Card("Hatsune Miku's screams.", true));
        whiteCards.add(new Card("School swimsuits.", true));
        whiteCards.add(new Card("Lovingly animated bouncing boobs.", true));
        whiteCards.add(new Card("Dragon Balls.", true));
        whiteCards.add(new Card("Zangief's chest hair.", true));
        whiteCards.add(new Card("DeviantArt.", true));
        whiteCards.add(new Card("Fiant fucking robots.", true));
        whiteCards.add(new Card("Crossplay.", true));
        whiteCards.add(new Card("Moeblob.", true));
        whiteCards.add(new Card("Carl Macek's rotting corpse.", true));
        whiteCards.add(new Card("My waifu.", true));
        whiteCards.add(new Card("Voice actress Megumi Hayashibara.", true));
        whiteCards.add(new Card("Lynn Minmei.", true));
        whiteCards.add(new Card("Panty shots.", true));
        whiteCards.add(new Card("Love and Justice.", true));
        whiteCards.add(new Card("Consensual tentacle rape.", true));
        whiteCards.add(new Card("Fundam.", true));
        whiteCards.add(new Card("Captain Bright slapping Amuro.", true));
        whiteCards.add(new Card("The Wave Undulation Cannon.", true));
        whiteCards.add(new Card("Having sex in the P.E. equipment shed.", true));
        whiteCards.add(new Card("Tainted sushi.", true));
        whiteCards.add(new Card("Shitty eurobeat music.", true));
        whiteCards.add(new Card("Bad dubbing.", true));
        whiteCards.add(new Card("Fangirls.", true));
        whiteCards.add(new Card("Kawaii desu uguu.", true));
        whiteCards.add(new Card("Futanari.", true));
        whiteCards.add(new Card("Lesbian schoolgirls.", true));
        whiteCards.add(new Card("Osamu Tezuka, rolling in his grave forever.", true));
        whiteCards.add(new Card("FUNimation.", true));
        whiteCards.add(new Card("Underage cosplayers in bondage gear.", true));
        whiteCards.add(new Card("Jackie Chan.", true));
        whiteCards.add(new Card("Exchanging Pocky for sexual favors.", true));
        whiteCards.add(new Card("Shipping.", true));
        whiteCards.add(new Card("Chiyo's father.", true));
        whiteCards.add(new Card("Magikarp.", true));
        whiteCards.add(new Card("Derpy.", true));
        whiteCards.add(new Card("Nanoha and her special friend Fate.", true));
        whiteCards.add(new Card("The marbles from Ramune bottles.", true));
        whiteCards.add(new Card("Wideface.", true));
        whiteCards.add(new Card("Spoilers.", true));
        whiteCards.add(new Card("Man-Faye.", true));
        whiteCards.add(new Card("Oppai mousepads.", true));
        whiteCards.add(new Card("Another dimension.", true));
        whiteCards.add(new Card("Homura sniffing Madoka's panties.", true));
        whiteCards.add(new Card("Hadouken.", true));
        whiteCards.add(new Card("Asian ball-jointed dolls.", true));
        whiteCards.add(new Card("J-list.", true));
        whiteCards.add(new Card("Childhood friends.", true));
        whiteCards.add(new Card("Monkey D. Luffy's rubbery cock.", true));
        whiteCards.add(new Card("Cloud's giant fucking Buster Swords.", true));
        whiteCards.add(new Card("Taking a dump in Char's helmet.", true));
        whiteCards.add(new Card("Hentai marathons.", true));
        whiteCards.add(new Card("Fothic Lolita.", true));
        whiteCards.add(new Card("Onaholes.", true));
        whiteCards.add(new Card("Super Saiyan Level 2.", true));
        whiteCards.add(new Card("Faia Online.", true));
        whiteCards.add(new Card("Santa's heavy sack.", true));
        whiteCards.add(new Card("Clearing a bloody path through Walmart with a scimitar.", true));
        whiteCards.add(new Card("Another shitty year.", true));
        whiteCards.add(new Card("Whatever Kwanzaa is supposed to be about.", true));
        whiteCards.add(new Card("A Christmas stocking full of coleslaw.", true));
        whiteCards.add(new Card("Elf cum.", true));
        whiteCards.add(new Card("The tiny, calloused hands of the Chinese children that made this card.", true));
        whiteCards.add(new Card("Taking down Santa with a surface-to-air missile.", true));
        whiteCards.add(new Card("Socks.", true));
        whiteCards.add(new Card("Pretending to be happy.", true));
        whiteCards.add(new Card("Krampus, the Austrian Christmas monster.", true));
        whiteCards.add(new Card("The Star Wars Holiday Special.", true));
        whiteCards.add(new Card("My hot cousin.", true));
        whiteCards.add(new Card("Mall Santa.", true));
        whiteCards.add(new Card("Several intertwining love stories featuring Hugh Grant.", true));
        whiteCards.add(new Card("A Hungry-Man; Frozen Christmas Dinner for one.", true));
        whiteCards.add(new Card("Fift-wrapping a live hamster.", true));
        whiteCards.add(new Card("Space Jam on VHS.", true));
        whiteCards.add(new Card("Immaculate conception.", true));
        whiteCards.add(new Card("Fucking up 'Silent Night' in front of 300 parents.", true));
        whiteCards.add(new Card("A visually arresting turtleneck.", true));
        whiteCards.add(new Card("A toxic family environment.", true));
        whiteCards.add(new Card("Eating an entire snowman.", true));
        whiteCards.add(new Card("Bumpses.", true));
        whiteCards.add(new Card("A Vin Gerard H8 X 10.", true));
        whiteCards.add(new Card("Harry Acropolis.", true));
        whiteCards.add(new Card("Under the ring.", true));
        whiteCards.add(new Card("Afa The Wild Samoan.", true));
        whiteCards.add(new Card("Peanut Butter and Baby sandwiches.", true));
        whiteCards.add(new Card("Yard Tards.", true));
        whiteCards.add(new Card("Two girls, one cup.", true));
        whiteCards.add(new Card("Ugly Mexican Hookers.", true));
        whiteCards.add(new Card("Duct tape.", true));
        whiteCards.add(new Card("Sodaj.", true));
        whiteCards.add(new Card("Steve The Teacher.", true));
        whiteCards.add(new Card("Jefferee.", true));
        whiteCards.add(new Card("Autoerotic Asphyxiation.", true));
        whiteCards.add(new Card("Sonic The Hedgehog.", true));
        whiteCards.add(new Card("Lotto Money.", true));
        whiteCards.add(new Card("Jailbait.", true));
        whiteCards.add(new Card("Prison rape.", true));
        whiteCards.add(new Card("Two And A Half Men.", true));
        whiteCards.add(new Card("Anne Frank.", true));
        whiteCards.add(new Card("Black Santa.", true));
        whiteCards.add(new Card("Jesus Christ (our lord and saviour, true)).", true));
        whiteCards.add(new Card("Farting with your armpits.", true));
        whiteCards.add(new Card("Poopsicles.", true));
        whiteCards.add(new Card("Slaughtering innocent children.", true));
        whiteCards.add(new Card("Sex with vegetables.", true));
        whiteCards.add(new Card("My gay ex-husband.", true));
        whiteCards.add(new Card("Accidentally sexting your mom.", true));
        whiteCards.add(new Card("Tabasco in your pee-hole.", true));
        whiteCards.add(new Card("Pee Wee Herman.", true));
        whiteCards.add(new Card("A breath of fresh air.", true));
        whiteCards.add(new Card("A great big floppy donkey dick.", true));
        whiteCards.add(new Card("A pyramid scheme.", true));
        whiteCards.add(new Card("A school bus surrounded by cop cars.", true));
        whiteCards.add(new Card("A short walk in the desert with shovels.", true));
        whiteCards.add(new Card("All the boys staring at your chest.", true));
        whiteCards.add(new Card("An amorous stallion.", true));
        whiteCards.add(new Card("Being so wet it just slides out of you.", true));
        whiteCards.add(new Card("Being tarred and feathered.", true));
        whiteCards.add(new Card("Catching 'em all.", true));
        whiteCards.add(new Card("Chained to the bed and whipped to orgasmic bliss by a leather-clad woman.", true));
        whiteCards.add(new Card("Child-bearing hips.", true));
        whiteCards.add(new Card("Defenestration.", true));
        whiteCards.add(new Card("Dungeons and/or dragons.", true));
        whiteCards.add(new Card("Ecco the Dolphin.", true));
        whiteCards.add(new Card("Feorge Washington riding on a giant eagle.", true));
        whiteCards.add(new Card("Fetting abducted and probed by aliens.", true));
        whiteCards.add(new Card("Foing viral on YouTube.", true));
        whiteCards.add(new Card("Fushing.", true));
        whiteCards.add(new Card("Making the baby Jesus cry.", true));
        whiteCards.add(new Card("More than you can chew.", true));
        whiteCards.add(new Card("Napalm.", true));
        whiteCards.add(new Card("Pancake bitches.", true));
        whiteCards.add(new Card("Playing God with the power of lightning.", true));
        whiteCards.add(new Card("Playing tonsil-hockey.", true));
        whiteCards.add(new Card("Racing cheese wheels downhill.", true));
        whiteCards.add(new Card("Riding the bomb.", true));
        whiteCards.add(new Card("Settling arguments with dance-offs.", true));
        whiteCards.add(new Card("Sheer spite.", true));
        whiteCards.add(new Card("Sinister laughter.", true));
        whiteCards.add(new Card("SS Girls.", true));
        whiteCards.add(new Card("Stealing your sister's underwear.", true));
        whiteCards.add(new Card("Stroking a cat the wrong way.", true));
        whiteCards.add(new Card("Sucking and blowing.", true));
        whiteCards.add(new Card("The bullet with your name on it.", true));
        whiteCards.add(new Card("The entire rest of eternity, spent in fucking Bruges.", true));
        whiteCards.add(new Card("The oceans rising to reclaim the land.", true));
        whiteCards.add(new Card("A cocained-fuelled sex orgy heart attack.", true));
        whiteCards.add(new Card("A cocktail umbrella", true));
        whiteCards.add(new Card("A murder/suicide pact.", true));
        whiteCards.add(new Card("A squirming mass of kittens.", true));
        whiteCards.add(new Card("An angry mob with torches and pitchforks.", true));
        whiteCards.add(new Card("Biting my girlfriend like a vampire during sex.", true));
        whiteCards.add(new Card("Dropping your pants and saluting.", true));
        whiteCards.add(new Card("Frankenstein's Monster", true));
        whiteCards.add(new Card("Fetting a blowjob in a theater.", true));
        whiteCards.add(new Card("Foing full retard.", true));
        whiteCards.add(new Card("Foing slob-slob-slob all over that knob.", true));
        whiteCards.add(new Card("Leaking implants.", true));
        whiteCards.add(new Card("Low-flying planes.", true));
        whiteCards.add(new Card("Monkies flinging their own shit.", true));
        whiteCards.add(new Card("My robot duplicate.", true));
        whiteCards.add(new Card("Other people’s children.", true));
        whiteCards.add(new Card("People who can't take a joke. Seriously.", true));
        whiteCards.add(new Card("Popping a boner during Sex Ed class.", true));
        whiteCards.add(new Card("Projectile vomiting.", true));
        whiteCards.add(new Card("Pulling down panties with your teeth.", true));
        whiteCards.add(new Card("Saying", true));
        whiteCards.add(new Card("Shedding skin like a snake.", true));
        whiteCards.add(new Card("Shooting Valley Girls for like, saying like all the time. Really.", true));
        whiteCards.add(new Card("Slow seductive tentacle rape.", true));
        whiteCards.add(new Card("Talking like a pirate, y’arr!", true));
        whiteCards.add(new Card("Tenderly kissing a unicorn's horn.", true));
        whiteCards.add(new Card("That bastard Jesus!", true));
        whiteCards.add(new Card("The last shreads of dignity.", true));
        whiteCards.add(new Card("The power of friendship.", true));
        whiteCards.add(new Card("This card intentionally left blank.", true));
        whiteCards.add(new Card("Throwing water on a braless woman in a white t-shirt", true));
        whiteCards.add(new Card("Upskirts.", true));
        whiteCards.add(new Card("Wasting all your money on hookers and booze.", true));
        whiteCards.add(new Card("Winning.", true));
        whiteCards.add(new Card("A foot fetish.", true));
        whiteCards.add(new Card("A powerful gag reflex.", true));
        whiteCards.add(new Card("A tight, Asian pussy.", true));
        whiteCards.add(new Card("Explosive decompression.", true));
        whiteCards.add(new Card("Extraordinary Rendition.", true));
        whiteCards.add(new Card("Forgetting the safety word.", true));
        whiteCards.add(new Card("Freeting Christmas carollers naked.", true));
        whiteCards.add(new Card("Handcuffs, without the key.", true));
        whiteCards.add(new Card("Having a drill for a penis.", true));
        whiteCards.add(new Card("Hot Jailbait Ass.", true));
        whiteCards.add(new Card("Liposuction gone horrible wrong.", true));
        whiteCards.add(new Card("My harem of scantily clad women.", true));
        whiteCards.add(new Card("Nazi Zombie Robot Ninjas.", true));
        whiteCards.add(new Card("Redneck gypsies.", true));
        whiteCards.add(new Card("Scissoring.", true));
        whiteCards.add(new Card("A guy and two robots who won’t shut up.", true));
        whiteCards.add(new Card("A shotgun wedding.", true));
        whiteCards.add(new Card("Anne Frank's diary", true));
        whiteCards.add(new Card("Autoerotic asphyxiation.", true));
        whiteCards.add(new Card("Blow Up Bianca the Latex Lovedoll.", true));
        whiteCards.add(new Card("Endlessly tumbling down an up escalator.", true));
        whiteCards.add(new Card("Fun with nuns.", true));
        whiteCards.add(new Card("Fetting it all over the walls.", true));
        whiteCards.add(new Card("Holiday Dinner by Jack Daniels.", true));
        whiteCards.add(new Card("Nailgun fights.", true));
        whiteCards.add(new Card("Teaching the bitch a lesson.", true));
        whiteCards.add(new Card("Nazi super science.", true));
        whiteCards.add(new Card("Making a human centipede.", true));
        whiteCards.add(new Card("The primal, ball-slapping sex your parents are having right now.", true));
        whiteCards.add(new Card("A cat video so cute that your eyes roll back and your spine slides out of your anus.", true));
        whiteCards.add(new Card("Cock.", true));
        whiteCards.add(new Card("A cop who is also a dog.", true));
        whiteCards.add(new Card("Dying alone and in pain.", true));
        whiteCards.add(new Card("Fay aliens.", true));
        whiteCards.add(new Card("The way white people is.", true));
        whiteCards.add(new Card("Reverse cowgirl.", true));
        whiteCards.add(new Card("The Quesadilla Explosion Salad from Chili's.", true));
        whiteCards.add(new Card("Actually getting shot, for real.", true));
        whiteCards.add(new Card("Not having sex.", true));
        whiteCards.add(new Card("Vietnam flashbacks.", true));
        whiteCards.add(new Card("Running naked through a mall, pissing and shitting everywhere.", true));
        whiteCards.add(new Card("Nothing.", true));
        whiteCards.add(new Card("Warm, velvety muppet sex.", true));
        whiteCards.add(new Card("Self-flagellation.", true));
        whiteCards.add(new Card("The systematic destruction of an entire people and their way of life.", true));
        whiteCards.add(new Card("Samuel L. Jackson.", true));
        whiteCards.add(new Card("A boo-boo.", true));
        whiteCards.add(new Card("Foing around punching people.", true));
        whiteCards.add(new Card("The entire Internet.", true));
        whiteCards.add(new Card("Some kind of bird-man.", true));
        whiteCards.add(new Card("Chugging a lava lamp.", true));
        whiteCards.add(new Card("Having sex on top of a pizza.", true));
        whiteCards.add(new Card("Indescribable loneliness.", true));
        whiteCards.add(new Card("An ass disaster.", true));
        whiteCards.add(new Card("Shutting the fuck up.", true));
        whiteCards.add(new Card("All my friends dying.", true));
        whiteCards.add(new Card("Putting an entire peanut butter and jelly sandwich into the VCR.", true));
        whiteCards.add(new Card("Spending lots of money.", true));
        whiteCards.add(new Card("Some douche with an acoustic guitar.", true));
        whiteCards.add(new Card("Flying robots that kill people.", true));
        whiteCards.add(new Card("A greased-up Matthew McConaughey.", true));
        whiteCards.add(new Card("An unstoppable wave of fire ants.", true));
        whiteCards.add(new Card("Not contributing to society in any meaningful way.", true));
        whiteCards.add(new Card("An all-midget production of Shakespeare's Richard III.", true));
        whiteCards.add(new Card("Screaming like a maniac.", true));
        whiteCards.add(new Card("The moist, demanding chasm of his mouth.", true));
        whiteCards.add(new Card("Filling every orifice with butterscotch pudding.", true));
        whiteCards.add(new Card("Unlimited soup, salad, and breadsticks.", true));
        whiteCards.add(new Card("Crying into the pages of Sylvia Plath.", true));
        whiteCards.add(new Card("Velcro.", true));
        whiteCards.add(new Card("A PowerPoint presentation.", true));
        whiteCards.add(new Card("A surprising amount of hair.", true));
        whiteCards.add(new Card("Eating Tom Selleck mustache to gain his powers.", true));
        whiteCards.add(new Card("Roland the Farter, flatulist to the king.", true));
        whiteCards.add(new Card("That ass.", true));
        whiteCards.add(new Card("A pile of squirming bodies.", true));
        whiteCards.add(new Card("Buying the right pants to be cool.", true));
        whiteCards.add(new Card("Blood farts.", true));
        whiteCards.add(new Card("Three months in the hole.", true));
        whiteCards.add(new Card("A botched circumcision.", true));
        whiteCards.add(new Card("The Land of Chocolate.", true));
        whiteCards.add(new Card("Slapping a racist old lady.", true));
        whiteCards.add(new Card("A lamprey swimming up the toilet and latching onto your taint.", true));
        whiteCards.add(new Card("Jumping out at people.", true));
        whiteCards.add(new Card("A black male in his early 20s, last seen wearing a hoodie.", true));
        whiteCards.add(new Card("Mufasa's death scene.", true));
        whiteCards.add(new Card("Bill Clinton, naked on a bearskin rug with a saxophone.", true));
        whiteCards.add(new Card("Demonic possession.", true));
        whiteCards.add(new Card("The Harlem Globetrotters.", true));
        whiteCards.add(new Card("Vomiting mid-blowjob.", true));
        whiteCards.add(new Card("My manservant, Claude.", true));
        whiteCards.add(new Card("Having shotguns for legs.", true));
        whiteCards.add(new Card("Letting everyone down.", true));
        whiteCards.add(new Card("A spontaneous conga line.", true));
        whiteCards.add(new Card("A vagina that leads to another dimension.", true));
        whiteCards.add(new Card("Disco fever.", true));
        whiteCards.add(new Card("Getting your dick stuck in a Chinese finger trap with another dick.", true));
        whiteCards.add(new Card("Fisting.", true));
        whiteCards.add(new Card("The thin veneer of situational causality that underlies porn.", true));
        whiteCards.add(new Card("Girls that always be textin'.", true));
        whiteCards.add(new Card("Blowing some dudes in an alley.", true));
        whiteCards.add(new Card("Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy.", true));
        whiteCards.add(new Card("Sneezing, farting, and coming at the same time.", true));
    }
}
