import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

public class JanelaPistas extends javax.swing.JFrame {
    private Tabuleiro tabuleiro;
    private AtorJogador ator;
    
    public JanelaPistas(Tabuleiro _tabuleiro, AtorJogador _ator) {
        initComponents();
        this.setTitle("Quadro de pistas");
        this.setSize(400, 300);
        
        tabuleiro = _tabuleiro;
        ator = _ator; 
        
        ArrayList<Pista> pistas = tabuleiro.getPistas();
        
        for(Pista p : pistas){
            CriaBotao(p);
        }        
    }

    private void ContinuarJogada(int idPista){
        this.dispose();
        tabuleiro.jogar(idPista, ator);
    }
    
    private void CriaBotao(Pista pista){
        JButton botao = new JButton();
        botao.setText(pista.getCategoria());
        botao.setSize(100,20);
        botao.setBackground(Color.blue);
        botao.setForeground(Color.yellow);
        boolean valido = !pista.isRespondida();
        botao.setEnabled(valido);
        int id = pista.getId();
        botao.setActionCommand(id + "");
        botao.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                ContinuarJogada(Integer.parseInt(arg0.getActionCommand()));
            }
        });        
        getContentPane().add(botao);      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
