/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceVisual;

import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JMenu;
import resources.Referencia;

/**
 *
 * @author Matheus
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        postInit();
    }

    void menuSuperiorVisivel(boolean visibilidade){
        barraMenuSuperior.setVisible(visibilidade);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        jMenuItem1 = new javax.swing.JMenuItem();
        barraMenuSuperior = new javax.swing.JMenuBar();
        menuOptionDesistir = new javax.swing.JMenu();
        menuItemDesistir = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        menuOptionDesistir.setText("Desistir");

        menuItemDesistir.setText("Desistir");
        menuOptionDesistir.add(menuItemDesistir);

        barraMenuSuperior.add(menuOptionDesistir);

        setJMenuBar(barraMenuSuperior);

        pack();
    }//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenuSuperior;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuItemDesistir;
    private javax.swing.JMenu menuOptionDesistir;
    // End of variables declaration//GEN-END:variables

    private void postInit() {
        try {
            setIconImage(ImageIO.read(Referencia.class.getResource("IconeJogoTransparente.png")));
        } catch (IOException ignored) {
            System.out.println("Icone da janela não encontrado.");
        }
        menuItemDesistir.addActionListener(evt ->{
            ControladorTelas.getInstance().desistir();
        });
    }
}
