/*
 * TelaCreditos.java
 *
 * Created on 15 de Agosto de 2006, 15:23
 */

package DaNumba;

/**
 * Classe que implementa a tela de créditos.
 * @author DaNumba
 */
public class TelaCreditos extends javax.swing.JDialog {
    
    /** Creates new form TelaCreditos */
    public TelaCreditos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 164, 0));
        setForeground(new java.awt.Color(255, 163, 0));
        setUndecorated(true);
        jPanel1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 164, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24));
        jLabel1.setText("Cr\u00e9ditos");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(95, 6, 112, 35);

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);
        jButton1.setBounds(125, 245, 50, 23);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextArea2.setBackground(new java.awt.Color(255, 164, 0));
        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Verdana", 0, 11));
        jTextArea2.setRows(5);
        jTextArea2.setText("Autores:\nLeonardo Becker Peres \n(leobp@inf.ufsc.br)\nRafael Moro de Andrade\n(rafinha@inf.ufsc.br)\n\nAn\u00e1lise e Projeto de Sistemas\nUFSC - Universidade Federal de Santa Catarina\n\nTodos os direitos reservados\nAgosto/2006");
        jTextArea2.setMargin(new java.awt.Insets(2, 4, 0, 0));
        jScrollPane1.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 280, 185);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 300, 280);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-300)/2, (screenSize.height-280)/2, 300, 280);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void mostrarTela(){ 
        setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    
}
