/*
 * TelaMensagem.java
 *
 * Created on 16 de Agosto de 2006, 16:49
 */

package DaNumba;

/**
 * Classe que implementa as mensagens do jogo.
  * @author DaNumba
 */
public class TelaMensagem extends javax.swing.JDialog {
    
    /** Creates new form TelaMensagem */
    public TelaMensagem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        jPanel1.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 164, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 300));
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);
        jButton1.setBounds(100, 117, 50, 23);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTextArea2.setBackground(new java.awt.Color(255, 164, 0));
        jTextArea2.setColumns(15);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Verdana", 1, 18));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(4);
        jTextArea2.setMargin(new java.awt.Insets(2, 4, 0, 0));
        jScrollPane1.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 230, 100);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 250, 150);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-250)/2, (screenSize.height-150)/2, 250, 150);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void mostrarTela(String pMsg){
        jTextArea2.setText(pMsg);
        jTextArea2.repaint();
        setVisible(true);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
    
}
